// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_FLIX_H
#define __BINDINGS_FLIX_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct flix_string_t {
  uint8_t*ptr;
  size_t len;
} flix_string_t;

// Logging/diagnostics.
typedef uint8_t flix_sys_sys_log_level_t;

#define FLIX_SYS_SYS_LOG_LEVEL_TRACE 0
#define FLIX_SYS_SYS_LOG_LEVEL_DEBUG 1
#define FLIX_SYS_SYS_LOG_LEVEL_INFO 2
#define FLIX_SYS_SYS_LOG_LEVEL_WARN 3
#define FLIX_SYS_SYS_LOG_LEVEL_ERROR 4

// Capability discovery.
// 
// This is intentionally coarse-grained; the portable stdlib should still
// treat capabilities as optional and return `Unsupported` when absent.
typedef uint8_t flix_sys_sys_capability_t;

#define FLIX_SYS_SYS_CAPABILITY_FILESYSTEM 0
#define FLIX_SYS_SYS_CAPABILITY_HTTP 1
#define FLIX_SYS_SYS_CAPABILITY_SOCKETS 2
#define FLIX_SYS_SYS_CAPABILITY_PROCESS 3
#define FLIX_SYS_SYS_CAPABILITY_THREADS 4

typedef struct {
  uint8_t *ptr;
  size_t len;
} flix_list_u8_t;

typedef struct {
  flix_string_t *ptr;
  size_t len;
} flix_list_string_t;

typedef struct exports_flix_runtime_runtime_own_ctx_t {
  int32_t __handle;
} exports_flix_runtime_runtime_own_ctx_t;

typedef struct exports_flix_runtime_runtime_ctx_t exports_flix_runtime_runtime_ctx_t;

typedef exports_flix_runtime_runtime_ctx_t* exports_flix_runtime_runtime_borrow_ctx_t;

typedef struct exports_flix_runtime_runtime_own_value_t {
  int32_t __handle;
} exports_flix_runtime_runtime_own_value_t;

typedef struct exports_flix_runtime_runtime_value_t exports_flix_runtime_runtime_value_t;

typedef exports_flix_runtime_runtime_value_t* exports_flix_runtime_runtime_borrow_value_t;

typedef struct exports_flix_runtime_runtime_own_suspension_t {
  int32_t __handle;
} exports_flix_runtime_runtime_own_suspension_t;

typedef struct exports_flix_runtime_runtime_suspension_t exports_flix_runtime_runtime_suspension_t;

typedef exports_flix_runtime_runtime_suspension_t* exports_flix_runtime_runtime_borrow_suspension_t;

// Stable symbol id (effect ids, op ids, def ids, etc).
typedef uint64_t exports_flix_runtime_runtime_sym_t;

// Stable exported definition id.
typedef uint64_t exports_flix_runtime_runtime_def_id_t;

// Host-visible id for a scheduled task (opaque to the host).
typedef uint64_t exports_flix_runtime_runtime_task_id_t;

// Suspension result produced by `invoke`.
// 
// `task` may be polled via `poll-task` to observe completion after resumption.
typedef struct exports_flix_runtime_runtime_suspended_exec_t {
  exports_flix_runtime_runtime_task_id_t   task;
  exports_flix_runtime_runtime_own_suspension_t   suspension;
} exports_flix_runtime_runtime_suspended_exec_t;

// Execution outcome.
typedef struct exports_flix_runtime_runtime_exec_t {
  uint8_t tag;
  union {
    exports_flix_runtime_runtime_own_value_t     ok;
    exports_flix_runtime_runtime_own_value_t     thrown;
    exports_flix_runtime_runtime_suspended_exec_t     suspended;
  } val;
} exports_flix_runtime_runtime_exec_t;

// Normal return with a value.
#define EXPORTS_FLIX_RUNTIME_RUNTIME_EXEC_OK 0
// Thrown exception as a designated `Exn` value.
#define EXPORTS_FLIX_RUNTIME_RUNTIME_EXEC_THROWN 1
// Suspended computation; host must resume later and poll the task.
#define EXPORTS_FLIX_RUNTIME_RUNTIME_EXEC_SUSPENDED 2

// Request payload for `timer-sleep` (host-backed).
typedef struct exports_flix_runtime_runtime_timer_sleep_req_t {
  uint64_t   ms;
} exports_flix_runtime_runtime_timer_sleep_req_t;

// HTTP header pair.
typedef struct exports_flix_runtime_runtime_http_header_t {
  flix_string_t   name;
  flix_string_t   value;
} exports_flix_runtime_runtime_http_header_t;

typedef struct {
  exports_flix_runtime_runtime_http_header_t *ptr;
  size_t len;
} exports_flix_runtime_runtime_list_http_header_t;

typedef struct {
  bool is_some;
  flix_string_t val;
} flix_option_string_t;

// Request payload for `http-request` (host-backed).
typedef struct exports_flix_runtime_runtime_http_request_req_t {
  flix_string_t   method;
  flix_string_t   url;
  exports_flix_runtime_runtime_list_http_header_t   headers;
  flix_option_string_t   body;
} exports_flix_runtime_runtime_http_request_req_t;

// HTTP response payload for `http-request` (host-backed).
typedef struct exports_flix_runtime_runtime_http_response_t {
  uint16_t   status;
  exports_flix_runtime_runtime_list_http_header_t   headers;
  flix_string_t   body;
} exports_flix_runtime_runtime_http_response_t;

// Portable IO error payload (matches `IoError.errorKindFromCode`).
typedef struct exports_flix_runtime_runtime_io_error_t {
  int32_t   kind_code;
  flix_string_t   msg;
} exports_flix_runtime_runtime_io_error_t;

// Request payload for `file-exists` (host-backed).
typedef struct exports_flix_runtime_runtime_file_exists_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_exists_req_t;

// Request payload for `file-is-directory` (host-backed).
typedef struct exports_flix_runtime_runtime_file_is_directory_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_is_directory_req_t;

// Request payload for `file-is-regular-file` (host-backed).
typedef struct exports_flix_runtime_runtime_file_is_regular_file_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_is_regular_file_req_t;

// Request payload for `file-is-readable` (host-backed).
typedef struct exports_flix_runtime_runtime_file_is_readable_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_is_readable_req_t;

// Request payload for `file-is-symbolic-link` (host-backed).
typedef struct exports_flix_runtime_runtime_file_is_symbolic_link_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_is_symbolic_link_req_t;

// Request payload for `file-is-writable` (host-backed).
typedef struct exports_flix_runtime_runtime_file_is_writable_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_is_writable_req_t;

// Request payload for `file-is-executable` (host-backed).
typedef struct exports_flix_runtime_runtime_file_is_executable_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_is_executable_req_t;

// Request payload for `file-access-time` (host-backed).
typedef struct exports_flix_runtime_runtime_file_access_time_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_access_time_req_t;

// Request payload for `file-creation-time` (host-backed).
typedef struct exports_flix_runtime_runtime_file_creation_time_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_creation_time_req_t;

// Request payload for `file-modification-time` (host-backed).
typedef struct exports_flix_runtime_runtime_file_modification_time_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_modification_time_req_t;

// Request payload for `file-size` (host-backed).
typedef struct exports_flix_runtime_runtime_file_size_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_size_req_t;

// Request payload for `file-read` (host-backed).
typedef struct exports_flix_runtime_runtime_file_read_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_read_req_t;

// Request payload for `file-read-lines` (host-backed).
typedef struct exports_flix_runtime_runtime_file_read_lines_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_read_lines_req_t;

// Request payload for `file-read-bytes` (host-backed).
typedef struct exports_flix_runtime_runtime_file_read_bytes_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_read_bytes_req_t;

// Request payload for `file-list` (host-backed).
typedef struct exports_flix_runtime_runtime_file_list_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_list_req_t;

// Request payload for `file-write` (host-backed).
typedef struct exports_flix_runtime_runtime_file_write_req_t {
  flix_string_t   path;
  flix_string_t   data;
} exports_flix_runtime_runtime_file_write_req_t;

// Request payload for `file-write-bytes` (host-backed).
typedef struct exports_flix_runtime_runtime_file_write_bytes_req_t {
  flix_string_t   path;
  flix_list_u8_t   bytes;
} exports_flix_runtime_runtime_file_write_bytes_req_t;

// Request payload for `file-append` (host-backed).
typedef struct exports_flix_runtime_runtime_file_append_req_t {
  flix_string_t   path;
  flix_string_t   data;
} exports_flix_runtime_runtime_file_append_req_t;

// Request payload for `file-append-bytes` (host-backed).
typedef struct exports_flix_runtime_runtime_file_append_bytes_req_t {
  flix_string_t   path;
  flix_list_u8_t   bytes;
} exports_flix_runtime_runtime_file_append_bytes_req_t;

// Request payload for `file-truncate` (host-backed).
typedef struct exports_flix_runtime_runtime_file_truncate_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_truncate_req_t;

// Request payload for `file-mkdir` (host-backed).
typedef struct exports_flix_runtime_runtime_file_mkdir_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_mkdir_req_t;

// Request payload for `file-mkdirs` (host-backed).
typedef struct exports_flix_runtime_runtime_file_mkdirs_req_t {
  flix_string_t   path;
} exports_flix_runtime_runtime_file_mkdirs_req_t;

// Request payload for `file-mk-temp-dir` (host-backed).
typedef struct exports_flix_runtime_runtime_file_mk_temp_dir_req_t {
  flix_string_t   prefix;
} exports_flix_runtime_runtime_file_mk_temp_dir_req_t;

// Environment variable entry for `process-exec`.
typedef struct exports_flix_runtime_runtime_process_env_var_t {
  flix_string_t   key;
  flix_string_t   value;
} exports_flix_runtime_runtime_process_env_var_t;

typedef struct {
  exports_flix_runtime_runtime_process_env_var_t *ptr;
  size_t len;
} exports_flix_runtime_runtime_list_process_env_var_t;

// Request payload for `process-exec` (host-backed).
typedef struct exports_flix_runtime_runtime_process_exec_req_t {
  // Command + arguments (argv[0] is the executable).
  flix_list_string_t   argv;
  // Working directory (optional).
  flix_option_string_t   cwd;
  // Environment variable overrides.
  exports_flix_runtime_runtime_list_process_env_var_t   env;
} exports_flix_runtime_runtime_process_exec_req_t;

// Request payload for `process-exit-value` (host-backed).
typedef struct exports_flix_runtime_runtime_process_exit_value_req_t {
  uint64_t   process_id;
} exports_flix_runtime_runtime_process_exit_value_req_t;

// Request payload for `process-is-alive` (host-backed).
typedef struct exports_flix_runtime_runtime_process_is_alive_req_t {
  uint64_t   process_id;
} exports_flix_runtime_runtime_process_is_alive_req_t;

// Request payload for `process-pid` (host-backed).
typedef struct exports_flix_runtime_runtime_process_pid_req_t {
  uint64_t   process_id;
} exports_flix_runtime_runtime_process_pid_req_t;

// Request payload for `process-stop` (host-backed).
typedef struct exports_flix_runtime_runtime_process_stop_req_t {
  uint64_t   process_id;
} exports_flix_runtime_runtime_process_stop_req_t;

// Request payload for `process-wait-for` (host-backed).
typedef struct exports_flix_runtime_runtime_process_wait_for_req_t {
  uint64_t   process_id;
} exports_flix_runtime_runtime_process_wait_for_req_t;

// Request payload for `process-wait-for-timeout` (host-backed).
typedef struct exports_flix_runtime_runtime_process_wait_for_timeout_req_t {
  uint64_t   process_id;
  int64_t   timeout_ms;
} exports_flix_runtime_runtime_process_wait_for_timeout_req_t;

// Request payload for `process-stdin-write` (host-backed).
typedef struct exports_flix_runtime_runtime_process_stdin_write_req_t {
  uint64_t   process_id;
  flix_list_u8_t   bytes;
} exports_flix_runtime_runtime_process_stdin_write_req_t;

// Request payload for `process-stdout-read` (host-backed).
typedef struct exports_flix_runtime_runtime_process_stdout_read_req_t {
  uint64_t   process_id;
  // Maximum number of bytes requested.
  uint32_t   max_bytes;
} exports_flix_runtime_runtime_process_stdout_read_req_t;

// Request payload for `process-stderr-read` (host-backed).
typedef struct exports_flix_runtime_runtime_process_stderr_read_req_t {
  uint64_t   process_id;
  // Maximum number of bytes requested.
  uint32_t   max_bytes;
} exports_flix_runtime_runtime_process_stderr_read_req_t;

// Request payload for `process-release` (host-backed).
typedef struct exports_flix_runtime_runtime_process_release_req_t {
  uint64_t   process_id;
} exports_flix_runtime_runtime_process_release_req_t;

// Request payload for `tcp-socket-connect` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_socket_connect_req_t {
  // IPv4 (4 bytes) or IPv6 (16 bytes).
  flix_list_u8_t   ip;
  // TCP port number.
  uint16_t   port;
} exports_flix_runtime_runtime_tcp_socket_connect_req_t;

// Request payload for `tcp-socket-read` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_socket_read_req_t {
  uint64_t   socket_id;
  // Maximum number of bytes requested.
  uint32_t   max_bytes;
} exports_flix_runtime_runtime_tcp_socket_read_req_t;

// Request payload for `tcp-socket-write` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_socket_write_req_t {
  uint64_t   socket_id;
  flix_list_u8_t   bytes;
} exports_flix_runtime_runtime_tcp_socket_write_req_t;

// Request payload for `tcp-socket-close` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_socket_close_req_t {
  uint64_t   socket_id;
} exports_flix_runtime_runtime_tcp_socket_close_req_t;

// Request payload for `tcp-server-bind` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_server_bind_req_t {
  // IPv4 (4 bytes) or IPv6 (16 bytes).
  flix_list_u8_t   ip;
  // TCP port number.
  uint16_t   port;
} exports_flix_runtime_runtime_tcp_server_bind_req_t;

// Request payload for `tcp-server-accept` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_server_accept_req_t {
  uint64_t   server_id;
} exports_flix_runtime_runtime_tcp_server_accept_req_t;

// Request payload for `tcp-server-local-port` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_server_local_port_req_t {
  uint64_t   server_id;
} exports_flix_runtime_runtime_tcp_server_local_port_req_t;

// Request payload for `tcp-server-close` (host-backed).
typedef struct exports_flix_runtime_runtime_tcp_server_close_req_t {
  uint64_t   server_id;
} exports_flix_runtime_runtime_tcp_server_close_req_t;

// Typed request for a suspended host operation.
typedef struct exports_flix_runtime_runtime_unknown_req_t {
  exports_flix_runtime_runtime_sym_t   eff_id;
  exports_flix_runtime_runtime_sym_t   op_id;
} exports_flix_runtime_runtime_unknown_req_t;

typedef struct exports_flix_runtime_runtime_op_request_t {
  uint8_t tag;
  union {
    exports_flix_runtime_runtime_timer_sleep_req_t     timer_sleep;
    exports_flix_runtime_runtime_http_request_req_t     http_request;
    exports_flix_runtime_runtime_file_exists_req_t     file_exists;
    exports_flix_runtime_runtime_file_is_directory_req_t     file_is_directory;
    exports_flix_runtime_runtime_file_is_regular_file_req_t     file_is_regular_file;
    exports_flix_runtime_runtime_file_is_readable_req_t     file_is_readable;
    exports_flix_runtime_runtime_file_is_symbolic_link_req_t     file_is_symbolic_link;
    exports_flix_runtime_runtime_file_is_writable_req_t     file_is_writable;
    exports_flix_runtime_runtime_file_is_executable_req_t     file_is_executable;
    exports_flix_runtime_runtime_file_access_time_req_t     file_access_time;
    exports_flix_runtime_runtime_file_creation_time_req_t     file_creation_time;
    exports_flix_runtime_runtime_file_modification_time_req_t     file_modification_time;
    exports_flix_runtime_runtime_file_size_req_t     file_size;
    exports_flix_runtime_runtime_file_read_req_t     file_read;
    exports_flix_runtime_runtime_file_read_lines_req_t     file_read_lines;
    exports_flix_runtime_runtime_file_read_bytes_req_t     file_read_bytes;
    exports_flix_runtime_runtime_file_list_req_t     file_list;
    exports_flix_runtime_runtime_file_write_req_t     file_write;
    exports_flix_runtime_runtime_file_write_bytes_req_t     file_write_bytes;
    exports_flix_runtime_runtime_file_append_req_t     file_append;
    exports_flix_runtime_runtime_file_append_bytes_req_t     file_append_bytes;
    exports_flix_runtime_runtime_file_truncate_req_t     file_truncate;
    exports_flix_runtime_runtime_file_mkdir_req_t     file_mkdir;
    exports_flix_runtime_runtime_file_mkdirs_req_t     file_mkdirs;
    exports_flix_runtime_runtime_file_mk_temp_dir_req_t     file_mk_temp_dir;
    exports_flix_runtime_runtime_process_exec_req_t     process_exec;
    exports_flix_runtime_runtime_process_exit_value_req_t     process_exit_value;
    exports_flix_runtime_runtime_process_is_alive_req_t     process_is_alive;
    exports_flix_runtime_runtime_process_pid_req_t     process_pid;
    exports_flix_runtime_runtime_process_stop_req_t     process_stop;
    exports_flix_runtime_runtime_process_wait_for_req_t     process_wait_for;
    exports_flix_runtime_runtime_process_wait_for_timeout_req_t     process_wait_for_timeout;
    exports_flix_runtime_runtime_process_stdin_write_req_t     process_stdin_write;
    exports_flix_runtime_runtime_process_stdout_read_req_t     process_stdout_read;
    exports_flix_runtime_runtime_process_stderr_read_req_t     process_stderr_read;
    exports_flix_runtime_runtime_process_release_req_t     process_release;
    exports_flix_runtime_runtime_tcp_socket_connect_req_t     tcp_socket_connect;
    exports_flix_runtime_runtime_tcp_socket_read_req_t     tcp_socket_read;
    exports_flix_runtime_runtime_tcp_socket_write_req_t     tcp_socket_write;
    exports_flix_runtime_runtime_tcp_socket_close_req_t     tcp_socket_close;
    exports_flix_runtime_runtime_tcp_server_bind_req_t     tcp_server_bind;
    exports_flix_runtime_runtime_tcp_server_accept_req_t     tcp_server_accept;
    exports_flix_runtime_runtime_tcp_server_local_port_req_t     tcp_server_local_port;
    exports_flix_runtime_runtime_tcp_server_close_req_t     tcp_server_close;
    exports_flix_runtime_runtime_unknown_req_t     unknown;
  } val;
} exports_flix_runtime_runtime_op_request_t;

#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TIMER_SLEEP 0
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_HTTP_REQUEST 1
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_EXISTS 2
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_IS_DIRECTORY 3
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_IS_REGULAR_FILE 4
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_IS_READABLE 5
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_IS_SYMBOLIC_LINK 6
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_IS_WRITABLE 7
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_IS_EXECUTABLE 8
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_ACCESS_TIME 9
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_CREATION_TIME 10
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_MODIFICATION_TIME 11
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_SIZE 12
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_READ 13
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_READ_LINES 14
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_READ_BYTES 15
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_LIST 16
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_WRITE 17
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_WRITE_BYTES 18
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_APPEND 19
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_APPEND_BYTES 20
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_TRUNCATE 21
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_MKDIR 22
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_MKDIRS 23
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_FILE_MK_TEMP_DIR 24
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_EXEC 25
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_EXIT_VALUE 26
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_IS_ALIVE 27
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_PID 28
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_STOP 29
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_WAIT_FOR 30
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_WAIT_FOR_TIMEOUT 31
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_STDIN_WRITE 32
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_STDOUT_READ 33
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_STDERR_READ 34
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_PROCESS_RELEASE 35
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SOCKET_CONNECT 36
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SOCKET_READ 37
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SOCKET_WRITE 38
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SOCKET_CLOSE 39
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SERVER_BIND 40
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SERVER_ACCEPT 41
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SERVER_LOCAL_PORT 42
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_TCP_SERVER_CLOSE 43
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_CONSOLE_READLN 44
#define EXPORTS_FLIX_RUNTIME_RUNTIME_OP_REQUEST_UNKNOWN 45

// Task completion outcome (never suspended).
typedef struct exports_flix_runtime_runtime_task_outcome_t {
  uint8_t tag;
  union {
    exports_flix_runtime_runtime_own_value_t     ok;
    exports_flix_runtime_runtime_own_value_t     thrown;
  } val;
} exports_flix_runtime_runtime_task_outcome_t;

// Normal return with a value.
#define EXPORTS_FLIX_RUNTIME_RUNTIME_TASK_OUTCOME_OK 0
// Thrown exception as a designated `Exn` value.
#define EXPORTS_FLIX_RUNTIME_RUNTIME_TASK_OUTCOME_THROWN 1

// Minimal suspension metadata.
typedef struct exports_flix_runtime_runtime_suspension_info_t {
  exports_flix_runtime_runtime_sym_t   eff_id;
  exports_flix_runtime_runtime_sym_t   op_id;
} exports_flix_runtime_runtime_suspension_info_t;

typedef struct {
  exports_flix_runtime_runtime_borrow_value_t *ptr;
  size_t len;
} exports_flix_runtime_runtime_list_borrow_value_t;

typedef struct {
  exports_flix_runtime_runtime_own_suspension_t *ptr;
  size_t len;
} exports_flix_runtime_runtime_list_own_suspension_t;

typedef struct {
  bool is_some;
  exports_flix_runtime_runtime_task_outcome_t val;
} exports_flix_runtime_runtime_option_task_outcome_t;

// Imported Functions from `flix:sys/sys@0.1.0`
// Log a message for debugging/diagnostics.
extern void flix_sys_sys_log(flix_sys_sys_log_level_t level, flix_string_t *msg);
// Return a monotonic-ish timestamp in milliseconds (best effort).
extern int64_t flix_sys_sys_time_now_ms(void);
// Return `len` random bytes.
extern void flix_sys_sys_random_bytes(uint32_t len, flix_list_u8_t *ret);
// Return the host-provided program arguments.
// 
// This mirrors `Env.getArgs` semantics: it must not include the program name.
// 
// Hosts may return an empty list when arguments are not meaningful (e.g. browsers).
extern void flix_sys_sys_get_args(flix_list_string_t *ret);
extern bool flix_sys_sys_has_capability(flix_sys_sys_capability_t cap);

// Exported Functions from `flix:runtime/runtime@0.1.0`
exports_flix_runtime_runtime_own_ctx_t exports_flix_runtime_runtime_new_ctx(void);
void exports_flix_runtime_runtime_invoke(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_def_id_t def_id, exports_flix_runtime_runtime_list_borrow_value_t *args, exports_flix_runtime_runtime_exec_t *ret);
exports_flix_runtime_runtime_task_id_t exports_flix_runtime_runtime_start_task(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_def_id_t def_id, exports_flix_runtime_runtime_list_borrow_value_t *args);
void exports_flix_runtime_runtime_sched_step(exports_flix_runtime_runtime_borrow_ctx_t ctx, uint32_t budget, exports_flix_runtime_runtime_list_own_suspension_t *ret);
bool exports_flix_runtime_runtime_poll_task(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_task_id_t task_id, exports_flix_runtime_runtime_task_outcome_t *ret);
void exports_flix_runtime_runtime_suspension_peek(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_suspension_t s, exports_flix_runtime_runtime_suspension_info_t *ret);
void exports_flix_runtime_runtime_suspension_request(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_suspension_t s, exports_flix_runtime_runtime_op_request_t *ret);
uint32_t exports_flix_runtime_runtime_suspension_arg_count(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_suspension_t s);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_suspension_arg_as_i64(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_suspension_t s, uint32_t idx);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_suspension_arg_as_ptr(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_suspension_t s, uint32_t idx);
void exports_flix_runtime_runtime_resume_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_borrow_value_t v);
void exports_flix_runtime_runtime_resume_throw(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_borrow_value_t e);
void exports_flix_runtime_runtime_resume_ok_sync(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_borrow_value_t v, exports_flix_runtime_runtime_exec_t *ret);
void exports_flix_runtime_runtime_resume_throw_sync(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_borrow_value_t e, exports_flix_runtime_runtime_exec_t *ret);
void exports_flix_runtime_runtime_resume_timer_sleep(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_console_readln_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_string_t *line);
void exports_flix_runtime_runtime_resume_http_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_http_response_t *resp);
void exports_flix_runtime_runtime_resume_http_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_exists_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool exists);
void exports_flix_runtime_runtime_resume_file_exists_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_is_directory_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool is_directory);
void exports_flix_runtime_runtime_resume_file_is_directory_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_is_regular_file_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool is_regular_file);
void exports_flix_runtime_runtime_resume_file_is_regular_file_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_is_readable_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool is_readable);
void exports_flix_runtime_runtime_resume_file_is_readable_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_is_symbolic_link_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool is_symbolic_link);
void exports_flix_runtime_runtime_resume_file_is_symbolic_link_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_is_writable_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool is_writable);
void exports_flix_runtime_runtime_resume_file_is_writable_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_is_executable_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool is_executable);
void exports_flix_runtime_runtime_resume_file_is_executable_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_access_time_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, int64_t ms);
void exports_flix_runtime_runtime_resume_file_access_time_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_creation_time_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, int64_t ms);
void exports_flix_runtime_runtime_resume_file_creation_time_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_modification_time_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, int64_t ms);
void exports_flix_runtime_runtime_resume_file_modification_time_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_size_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, int64_t bytes);
void exports_flix_runtime_runtime_resume_file_size_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_read_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_string_t *data);
void exports_flix_runtime_runtime_resume_file_read_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_read_lines_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_list_string_t *lines);
void exports_flix_runtime_runtime_resume_file_read_lines_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_read_bytes_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_list_u8_t *bytes);
void exports_flix_runtime_runtime_resume_file_read_bytes_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_list_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_list_string_t *names);
void exports_flix_runtime_runtime_resume_file_list_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_write_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_file_write_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_write_bytes_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_file_write_bytes_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_append_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_file_append_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_append_bytes_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_file_append_bytes_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_truncate_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_file_truncate_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_mkdir_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_file_mkdir_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_mkdirs_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_file_mkdirs_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_file_mk_temp_dir_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_string_t *path);
void exports_flix_runtime_runtime_resume_file_mk_temp_dir_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_exec_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, uint64_t process_id);
void exports_flix_runtime_runtime_resume_process_exec_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_exit_value_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, int32_t code);
void exports_flix_runtime_runtime_resume_process_exit_value_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_is_alive_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool is_alive);
void exports_flix_runtime_runtime_resume_process_is_alive_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_pid_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, int64_t pid);
void exports_flix_runtime_runtime_resume_process_pid_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_stop_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_process_stop_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_wait_for_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, int32_t code);
void exports_flix_runtime_runtime_resume_process_wait_for_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_wait_for_timeout_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, bool finished);
void exports_flix_runtime_runtime_resume_process_wait_for_timeout_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_stdin_write_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_process_stdin_write_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_stdout_read_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_list_u8_t *bytes);
void exports_flix_runtime_runtime_resume_process_stdout_read_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_stderr_read_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_list_u8_t *bytes);
void exports_flix_runtime_runtime_resume_process_stderr_read_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_process_release_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_process_release_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_socket_connect_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, uint64_t socket_id);
void exports_flix_runtime_runtime_resume_tcp_socket_connect_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_socket_read_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, flix_list_u8_t *bytes);
void exports_flix_runtime_runtime_resume_tcp_socket_read_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_socket_write_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_tcp_socket_write_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_socket_close_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_tcp_socket_close_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_server_bind_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, uint64_t server_id);
void exports_flix_runtime_runtime_resume_tcp_server_bind_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_server_accept_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, uint64_t socket_id);
void exports_flix_runtime_runtime_resume_tcp_server_accept_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_server_local_port_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, uint16_t port);
void exports_flix_runtime_runtime_resume_tcp_server_local_port_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
void exports_flix_runtime_runtime_resume_tcp_server_close_ok(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s);
void exports_flix_runtime_runtime_resume_tcp_server_close_err(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_own_suspension_t s, exports_flix_runtime_runtime_io_error_t *err_);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_i8(exports_flix_runtime_runtime_borrow_ctx_t ctx, int8_t x);
int8_t exports_flix_runtime_runtime_unbox_i8(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_i16(exports_flix_runtime_runtime_borrow_ctx_t ctx, int16_t x);
int16_t exports_flix_runtime_runtime_unbox_i16(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_i32(exports_flix_runtime_runtime_borrow_ctx_t ctx, int32_t x);
int32_t exports_flix_runtime_runtime_unbox_i32(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_i64(exports_flix_runtime_runtime_borrow_ctx_t ctx, int64_t x);
int64_t exports_flix_runtime_runtime_unbox_i64(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_f32(exports_flix_runtime_runtime_borrow_ctx_t ctx, float x);
float exports_flix_runtime_runtime_unbox_f32(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_f64(exports_flix_runtime_runtime_borrow_ctx_t ctx, double x);
double exports_flix_runtime_runtime_unbox_f64(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_bool(exports_flix_runtime_runtime_borrow_ctx_t ctx, bool b);
bool exports_flix_runtime_runtime_unbox_bool(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_string(exports_flix_runtime_runtime_borrow_ctx_t ctx, flix_string_t *s);
void exports_flix_runtime_runtime_unbox_string(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v, flix_string_t *ret);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_box_bytes(exports_flix_runtime_runtime_borrow_ctx_t ctx, flix_list_u8_t *bytes);
void exports_flix_runtime_runtime_unbox_bytes(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t v, flix_list_u8_t *ret);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_tuple_new(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_list_borrow_value_t *fields);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_tuple_field(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t tup, uint32_t idx);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_tag_new(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_sym_t tag_id, exports_flix_runtime_runtime_list_borrow_value_t *fields);
exports_flix_runtime_runtime_sym_t exports_flix_runtime_runtime_tag_id(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t tagged);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_tag_field_i64(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t tagged, uint32_t idx);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_tag_field_ptr(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t tagged, uint32_t idx);
uint32_t exports_flix_runtime_runtime_list_len(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t xs, exports_flix_runtime_runtime_sym_t nil_tag_id, exports_flix_runtime_runtime_sym_t cons_tag_id);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_array_new(exports_flix_runtime_runtime_borrow_ctx_t ctx, bool ptr_elems, exports_flix_runtime_runtime_list_borrow_value_t *elems);
uint32_t exports_flix_runtime_runtime_array_len(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t arr);
exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_array_elem(exports_flix_runtime_runtime_borrow_ctx_t ctx, exports_flix_runtime_runtime_borrow_value_t arr, uint32_t idx);

// Helper Functions

void flix_list_u8_free(flix_list_u8_t *ptr);

void flix_list_string_free(flix_list_string_t *ptr);

extern void exports_flix_runtime_runtime_ctx_drop_own(exports_flix_runtime_runtime_own_ctx_t handle);

extern exports_flix_runtime_runtime_own_ctx_t exports_flix_runtime_runtime_ctx_new(exports_flix_runtime_runtime_ctx_t *rep);
extern exports_flix_runtime_runtime_ctx_t* exports_flix_runtime_runtime_ctx_rep(exports_flix_runtime_runtime_own_ctx_t handle);
void exports_flix_runtime_runtime_ctx_destructor(exports_flix_runtime_runtime_ctx_t *rep);

extern void exports_flix_runtime_runtime_value_drop_own(exports_flix_runtime_runtime_own_value_t handle);

extern exports_flix_runtime_runtime_own_value_t exports_flix_runtime_runtime_value_new(exports_flix_runtime_runtime_value_t *rep);
extern exports_flix_runtime_runtime_value_t* exports_flix_runtime_runtime_value_rep(exports_flix_runtime_runtime_own_value_t handle);
void exports_flix_runtime_runtime_value_destructor(exports_flix_runtime_runtime_value_t *rep);

extern void exports_flix_runtime_runtime_suspension_drop_own(exports_flix_runtime_runtime_own_suspension_t handle);

extern exports_flix_runtime_runtime_own_suspension_t exports_flix_runtime_runtime_suspension_new(exports_flix_runtime_runtime_suspension_t *rep);
extern exports_flix_runtime_runtime_suspension_t* exports_flix_runtime_runtime_suspension_rep(exports_flix_runtime_runtime_own_suspension_t handle);
void exports_flix_runtime_runtime_suspension_destructor(exports_flix_runtime_runtime_suspension_t *rep);

void exports_flix_runtime_runtime_exec_free(exports_flix_runtime_runtime_exec_t *ptr);

void exports_flix_runtime_runtime_http_header_free(exports_flix_runtime_runtime_http_header_t *ptr);

void exports_flix_runtime_runtime_list_http_header_free(exports_flix_runtime_runtime_list_http_header_t *ptr);

void flix_option_string_free(flix_option_string_t *ptr);

void exports_flix_runtime_runtime_http_request_req_free(exports_flix_runtime_runtime_http_request_req_t *ptr);

void exports_flix_runtime_runtime_http_response_free(exports_flix_runtime_runtime_http_response_t *ptr);

void exports_flix_runtime_runtime_io_error_free(exports_flix_runtime_runtime_io_error_t *ptr);

void exports_flix_runtime_runtime_file_exists_req_free(exports_flix_runtime_runtime_file_exists_req_t *ptr);

void exports_flix_runtime_runtime_file_is_directory_req_free(exports_flix_runtime_runtime_file_is_directory_req_t *ptr);

void exports_flix_runtime_runtime_file_is_regular_file_req_free(exports_flix_runtime_runtime_file_is_regular_file_req_t *ptr);

void exports_flix_runtime_runtime_file_is_readable_req_free(exports_flix_runtime_runtime_file_is_readable_req_t *ptr);

void exports_flix_runtime_runtime_file_is_symbolic_link_req_free(exports_flix_runtime_runtime_file_is_symbolic_link_req_t *ptr);

void exports_flix_runtime_runtime_file_is_writable_req_free(exports_flix_runtime_runtime_file_is_writable_req_t *ptr);

void exports_flix_runtime_runtime_file_is_executable_req_free(exports_flix_runtime_runtime_file_is_executable_req_t *ptr);

void exports_flix_runtime_runtime_file_access_time_req_free(exports_flix_runtime_runtime_file_access_time_req_t *ptr);

void exports_flix_runtime_runtime_file_creation_time_req_free(exports_flix_runtime_runtime_file_creation_time_req_t *ptr);

void exports_flix_runtime_runtime_file_modification_time_req_free(exports_flix_runtime_runtime_file_modification_time_req_t *ptr);

void exports_flix_runtime_runtime_file_size_req_free(exports_flix_runtime_runtime_file_size_req_t *ptr);

void exports_flix_runtime_runtime_file_read_req_free(exports_flix_runtime_runtime_file_read_req_t *ptr);

void exports_flix_runtime_runtime_file_read_lines_req_free(exports_flix_runtime_runtime_file_read_lines_req_t *ptr);

void exports_flix_runtime_runtime_file_read_bytes_req_free(exports_flix_runtime_runtime_file_read_bytes_req_t *ptr);

void exports_flix_runtime_runtime_file_list_req_free(exports_flix_runtime_runtime_file_list_req_t *ptr);

void exports_flix_runtime_runtime_file_write_req_free(exports_flix_runtime_runtime_file_write_req_t *ptr);

void exports_flix_runtime_runtime_file_write_bytes_req_free(exports_flix_runtime_runtime_file_write_bytes_req_t *ptr);

void exports_flix_runtime_runtime_file_append_req_free(exports_flix_runtime_runtime_file_append_req_t *ptr);

void exports_flix_runtime_runtime_file_append_bytes_req_free(exports_flix_runtime_runtime_file_append_bytes_req_t *ptr);

void exports_flix_runtime_runtime_file_truncate_req_free(exports_flix_runtime_runtime_file_truncate_req_t *ptr);

void exports_flix_runtime_runtime_file_mkdir_req_free(exports_flix_runtime_runtime_file_mkdir_req_t *ptr);

void exports_flix_runtime_runtime_file_mkdirs_req_free(exports_flix_runtime_runtime_file_mkdirs_req_t *ptr);

void exports_flix_runtime_runtime_file_mk_temp_dir_req_free(exports_flix_runtime_runtime_file_mk_temp_dir_req_t *ptr);

void exports_flix_runtime_runtime_process_env_var_free(exports_flix_runtime_runtime_process_env_var_t *ptr);

void exports_flix_runtime_runtime_list_process_env_var_free(exports_flix_runtime_runtime_list_process_env_var_t *ptr);

void exports_flix_runtime_runtime_process_exec_req_free(exports_flix_runtime_runtime_process_exec_req_t *ptr);

void exports_flix_runtime_runtime_op_request_free(exports_flix_runtime_runtime_op_request_t *ptr);

void exports_flix_runtime_runtime_task_outcome_free(exports_flix_runtime_runtime_task_outcome_t *ptr);

void exports_flix_runtime_runtime_list_borrow_value_free(exports_flix_runtime_runtime_list_borrow_value_t *ptr);

void exports_flix_runtime_runtime_list_own_suspension_free(exports_flix_runtime_runtime_list_own_suspension_t *ptr);

void exports_flix_runtime_runtime_option_task_outcome_free(exports_flix_runtime_runtime_option_task_outcome_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void flix_string_set(flix_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void flix_string_dup(flix_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void flix_string_dup_n(flix_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void flix_string_free(flix_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
