/*
 * Copyright 2026 Magnus Madsen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix.language.phase.llvm

import ca.uwaterloo.flix.api.Flix
import ca.uwaterloo.flix.language.phase.ExportAbi
import ca.uwaterloo.flix.language.phase.ExportAbi.AbiType
import ca.uwaterloo.flix.language.phase.WasmImportInterface
import ca.uwaterloo.flix.util.{ArtifactNames, InternalCompilerException}

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, LinkOption, Path}
import scala.collection.mutable

/**
  * Writes typed JavaScript/TypeScript convenience bindings for wasm `@Export` defs.
  *
  * These bindings are intentionally thin wrappers over the public typed wasm export component.
  * They do not reintroduce the internal `flix:runtime/runtime` substrate.
  */
object LlvmWasmBindingWriter {

  case class Artifacts(js: Path, dts: Path)

  def run(root: ca.uwaterloo.flix.language.ast.LoweredAst.Root)(implicit flix: Flix): Option[Artifacts] = {
    val exports = LlvmWasmTypedExportsWriter.compute(root)
    if (exports.isEmpty) return None
    val wasmImports = LlvmWasmImportsWriter.compute(root)

    Some(write(exports, wasmImports, LlvmWasmDriver.jsOutDirPath(flix.options.outputPath), flix.options.artifactName))
  }

  def bindingsJsPath(outputPath: Path, artifactName: String = ArtifactNames.DefaultBaseName): Path =
    LlvmWasmDriver.jsOutDirPath(outputPath).resolve(ArtifactNames.wasmBindingsJsFileName(artifactName)).toAbsolutePath.normalize()

  def bindingsTypesPath(outputPath: Path, artifactName: String = ArtifactNames.DefaultBaseName): Path =
    LlvmWasmDriver.jsOutDirPath(outputPath).resolve(ArtifactNames.wasmBindingsTypesFileName(artifactName)).toAbsolutePath.normalize()

  private[llvm] def write(exports: List[LlvmWasmTypedExportsWriter.Entry], wasmImports: List[LlvmWasmImportsWriter.Entry], outputDir: Path, artifactName: String): Artifacts = {
    val jsPath = outputDir.resolve(ArtifactNames.wasmBindingsJsFileName(artifactName)).toAbsolutePath.normalize()
    val dtsPath = outputDir.resolve(ArtifactNames.wasmBindingsTypesFileName(artifactName)).toAbsolutePath.normalize()

    writeFile(jsPath, renderJs(exports, wasmImports, artifactName).getBytes(StandardCharsets.UTF_8))
    writeFile(dtsPath, renderDts(exports, wasmImports, artifactName).getBytes(StandardCharsets.UTF_8))

    Artifacts(jsPath, dtsPath)
  }

  private def renderJs(exports: List[LlvmWasmTypedExportsWriter.Entry], wasmImports: List[LlvmWasmImportsWriter.Entry], artifactName: String): String = {
    val sb = new StringBuilder(12 * 1024)
    val aggTypes = aggregateTypes(exports, wasmImports)
    val importsByInterface = wasmImports.groupBy(_.interfaceId).toList.sortBy(_._1.qualifiedInterface)

    sb.append("// Generated by the Flix compiler (LLVM-wasm typed export bindings)\n")
    sb.append("// NOTE: This file is a thin convenience layer over the public typed wasm export component.\n")
    sb.append(s"""import { api } from "./${ArtifactNames.wasmTypedExportComponentJsFileName(artifactName)}";\n""")
    importsByInterface.foreach { case (id, _) =>
      sb.append(s"""import { ${id.jsSetterName} } from "./${id.jsModuleFileName}";\n""")
    }
    sb.append("\n")
    sb.append("export { api };\n")
    sb.append("\n")
    sb.append("export function configureImports(imports = {}) {\n")
    importsByInterface.foreach { case (id, entries) =>
      sb.append(s"""  const raw_${id.jsModuleBaseName} = imports[${renderJsString(id.qualifiedInterface)}] ?? {};\n""")
      sb.append(s"""  ${id.jsSetterName}({\n""")
      entries.groupBy(_.spec.func).toList.sortBy(_._1).foreach { case (func, overloads) =>
        val entry = overloads.head
        val args = entry.signature.params.zipWithIndex.map {
          case (tpe, idx) => fromWireExpr(tpe, s"a$idx")
        }.mkString(", ")
        val result = toWireExpr(entry.signature.result, "result")
        val rawAccess = jsPropAccess(s"raw_${id.jsModuleBaseName}", WasmImportInterface.jsName(func))
        sb.append(s"""    ${renderJsString(func)}: (${entry.signature.params.indices.map(i => s"a$i").mkString(", ")}) => {\n""")
        sb.append(s"      const fn = $rawAccess;\n")
        sb.append("      if (typeof fn !== \"function\") {\n")
        sb.append(s"""        throw new Error("Missing JS host implementation for ${escapeJsString(id.qualifiedInterface)}#${escapeJsString(func)}");\n""")
        sb.append("      }\n")
        sb.append(s"      const result = fn(${args});\n")
        sb.append(s"      return $result;\n")
        sb.append("    },\n")
      }
      sb.append("  });\n")
    }
    sb.append("}\n")
    sb.append("\n")
    sb.append("export function newCtx() {\n")
    sb.append("  return new api.Ctx();\n")
    sb.append("}\n")
    sb.append("\n")

    aggTypes.foreach { tpe =>
      sb.append(renderJsDefaultHelper(tpe))
      sb.append("\n")
      sb.append(renderJsToWireHelper(tpe))
      sb.append("\n")
      sb.append(renderJsFromWireHelper(tpe))
      sb.append("\n")
    }

    resultTypes(exports).foreach { tpe =>
      sb.append(renderJsExecHelper(tpe))
      sb.append("\n")
    }

    exports.foreach { e =>
      val jsArgs = e.signature.params.indices.map(idx => s"a$idx").toList
      val callName = flatFunctionName(e.symbol)
      val resumeName = flatResumeFunctionName(e.symbol)
      val requestName = flatRequestFunctionName(e.symbol)
      val ctxMethod = jsMethodNameFromWitName(e.witName)
      val ctxResumeMethod = jsMethodNameFromWitName(s"resume-${e.witName}")
      val ctxRequestMethod = jsMethodNameFromWitName(s"request-${e.witName}")
      val convertedArgs = e.signature.params.zip(jsArgs).map {
        case (tpe, arg) => toWireExpr(tpe, arg)
      }
      val callExpr = s"ctx.$ctxMethod(${convertedArgs.mkString(", ")})"
      val resumeArg = e.resumeType match {
        case Some(tpe) => toWireExpr(tpe, "resume")
        case None => "resume"
      }
      val resumeExpr = s"ctx.$ctxResumeMethod(suspension, $resumeArg)"
      val callReturn = fromExecExpr(e.signature.result, callExpr)
      val resumeReturn = fromExecExpr(e.signature.result, resumeExpr)

      sb.append(s"export function $callName(ctx${if (jsArgs.nonEmpty) ", " else ""}${jsArgs.mkString(", ")}) {\n")
      sb.append(s"  return $callReturn;\n")
      sb.append("}\n\n")

      sb.append(s"export function $resumeName(ctx, suspension, resume) {\n")
      sb.append(s"  return $resumeReturn;\n")
      sb.append("}\n\n")

      e.requestSignature.foreach { sig =>
        sb.append(s"export function $requestName(ctx, suspension) {\n")
        sb.append(s"  return ${fromRequestExpr(sig.params, s"ctx.$ctxRequestMethod(suspension)")};\n")
        sb.append("}\n\n")
      }
    }

    sb.append("export const metadata = {\n")
    exports.zipWithIndex.foreach { case (e, idx) =>
      val params = e.signature.params.map(p => "\"" + p.displayName + "\"").mkString(", ")
      sb.append(s"""  "${escapeJsString(e.symbol)}": { defId: ${e.defId}n, params: [$params], result: "${e.signature.result.displayName}" }""")
      if (idx != exports.length - 1) sb.append(",")
      sb.append("\n")
    }
    sb.append("};\n\n")

    sb.append("export const Exports = ")
    sb.append(renderTree(buildTree(exports), leaf => leaf.fnName))
    sb.append(";\n")

    sb.toString()
  }

  private def renderDts(exports: List[LlvmWasmTypedExportsWriter.Entry], wasmImports: List[LlvmWasmImportsWriter.Entry], artifactName: String): String = {
    val sb = new StringBuilder(10 * 1024)
    val importsByInterface = wasmImports.groupBy(_.interfaceId).toList.sortBy(_._1.qualifiedInterface)

    sb.append("// Generated by the Flix compiler (LLVM-wasm typed export bindings)\n")
    sb.append(s"""import type * as TypedExports from "./${ArtifactNames.wasmTypedExportComponentJsFileName(artifactName)}";\n""")
    sb.append(s"""export { api } from "./${ArtifactNames.wasmTypedExportComponentJsFileName(artifactName)}";\n\n""")
    sb.append("export type FlixCtx = TypedExports.api.Ctx;\n")
    sb.append("export type FlixValue = TypedExports.api.Value;\n")
    sb.append("export type FlixSuspension = TypedExports.api.Suspension;\n\n")
    sb.append("export type FlixExec<T> =\n")
    sb.append("""  | { tag: "ok"; val: T }""" + "\n")
    sb.append("""  | { tag: "thrown"; val: TypedExports.api.Value }""" + "\n")
    sb.append("""  | { tag: "suspended"; val: TypedExports.api.Suspension };""" + "\n\n")
    sb.append("export interface WasmImports {\n")
    importsByInterface.foreach { case (id, entries) =>
      sb.append(s"""  ${renderJsString(id.qualifiedInterface)}?: {\n""")
      entries.groupBy(_.spec.func).toList.sortBy(_._1).foreach { case (func, overloads) =>
        val entry = overloads.head
        val args = entry.signature.params.zipWithIndex.map {
          case (tpe, idx) => s"a$idx: ${tsTypeOf(tpe)}"
        }.mkString(", ")
        val result = tsTypeOf(entry.signature.result)
        sb.append(s"""    ${tsFieldName(WasmImportInterface.jsName(func))}?: (${args}) => ${result};\n""")
      }
      sb.append("  };\n")
    }
    sb.append("}\n\n")
    sb.append("export function configureImports(imports?: WasmImports): void;\n")
    sb.append("export function newCtx(): TypedExports.api.Ctx;\n")
    sb.append("export const metadata: Record<string, { defId: bigint; params: readonly string[]; result: string }>;\n\n")

    exports.foreach { e =>
      val callName = flatFunctionName(e.symbol)
      val resumeName = flatResumeFunctionName(e.symbol)
      val requestName = flatRequestFunctionName(e.symbol)
      val args = e.signature.params.zipWithIndex.map {
        case (tpe, idx) => s"a$idx: ${tsTypeOf(tpe)}"
      }.mkString(", ")
      sb.append(s"export function $callName(ctx: TypedExports.api.Ctx${if (args.nonEmpty) ", " else ""}$args): ${tsExecTypeOf(e.signature.result)};\n")
      val resumeTsType = e.resumeType match {
        case Some(tpe) => tsTypeOf(tpe)
        case None => "TypedExports.api.Value"
      }
      sb.append(s"export function $resumeName(ctx: TypedExports.api.Ctx, suspension: TypedExports.api.Suspension, resume: $resumeTsType): ${tsExecTypeOf(e.signature.result)};\n")
      e.requestSignature.foreach { sig =>
        sb.append(s"export function $requestName(ctx: TypedExports.api.Ctx, suspension: TypedExports.api.Suspension): ${tsRequestTypeOf(sig.params)};\n")
      }
    }
    sb.append("\n")
    sb.append("export const Exports: ")
    sb.append(renderTree(buildTree(exports), leaf => s"typeof ${leaf.fnName}"))
    sb.append(";\n")

    sb.toString()
  }

  private def tsTypeOf(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "void"
    case AbiType.Bool => "boolean"
    case AbiType.Int8 | AbiType.Int16 | AbiType.Int32 | AbiType.Float32 | AbiType.Float64 => "number"
    case AbiType.Int64 => "bigint"
    case AbiType.String => "string"
    case AbiType.Bytes => "Uint8Array"
    case AbiType.List(elm) => s"ReadonlyArray<${tsTypeOf(elm)}>"
    case AbiType.Array(elm) => s"ReadonlyArray<${tsTypeOf(elm)}>"
    case AbiType.Tuple(elms) => s"readonly [${elms.map(tsTypeOf).mkString(", ")}]"
    case AbiType.Record(fields) =>
      fields.map { case (label, fieldTpe) => s"readonly ${tsFieldName(label)}: ${tsTypeOf(fieldTpe)}" }.mkString("{ ", "; ", " }")
    case AbiType.Option(elm) => s"${tsTypeOf(elm)} | null"
    case AbiType.Result(ok, err) => s"""{ tag: "ok"; val: ${tsTypeOf(ok)} } | { tag: "err"; val: ${tsTypeOf(err)} }"""
  }

  private def tsExecTypeOf(tpe: AbiType): String =
    s"FlixExec<${tsTypeOf(tpe)}>"

  private def aggregateTypes(exports: List[LlvmWasmTypedExportsWriter.Entry], wasmImports: List[LlvmWasmImportsWriter.Entry]): List[AbiType] = {
    val out = mutable.LinkedHashMap.empty[String, AbiType]

    def visit(tpe: AbiType): Unit = tpe match {
      case seq@AbiType.List(elm) =>
        visit(elm)
        out.getOrElseUpdate(seq.stableId, seq)
      case seq@AbiType.Array(elm) =>
        visit(elm)
        out.getOrElseUpdate(seq.stableId, seq)
      case tup@AbiType.Tuple(elms) =>
        elms.foreach(visit)
        out.getOrElseUpdate(tup.stableId, tup)
      case rec@AbiType.Record(fields) =>
        fields.foreach { case (_, fieldTpe) => visit(fieldTpe) }
        out.getOrElseUpdate(rec.stableId, rec)
      case opt@AbiType.Option(elm) =>
        visit(elm)
        out.getOrElseUpdate(opt.stableId, opt)
      case res@AbiType.Result(ok, err) =>
        visit(ok)
        visit(err)
        out.getOrElseUpdate(res.stableId, res)
      case _ => ()
    }

    exports.foreach { e =>
      e.signature.params.foreach(visit)
      visit(e.signature.result)
      e.resumeType.foreach(visit)
      e.requestSignature.foreach { sig =>
        sig.params.foreach(visit)
        visit(sig.result)
      }
    }
    wasmImports.foreach { e =>
      e.signature.params.foreach(visit)
      visit(e.signature.result)
    }

    out.values.toList
  }

  private def resultTypes(exports: List[LlvmWasmTypedExportsWriter.Entry]): List[AbiType] =
    exports.iterator.map(_.signature.result).toList.distinct.sortBy(_.displayName)

  private def renderJsDefaultHelper(tpe: AbiType): String =
    s"""function ${jsDefaultHelperName(tpe)}() {
       |  return ${defaultJsExpr(tpe)};
       |}
       |""".stripMargin

  private def renderJsToWireHelper(tpe: AbiType): String =
    s"""function ${jsToWireHelperName(tpe)}(x) {
       |  return ${toWireExpr(tpe, "x")};
       |}
       |""".stripMargin

  private def renderJsFromWireHelper(tpe: AbiType): String =
    s"""function ${jsFromWireHelperName(tpe)}(x) {
       |  return ${fromWireExpr(tpe, "x")};
       |}
       |""".stripMargin

  private def renderJsExecHelper(tpe: AbiType): String = {
    val fn = jsExecHelperName(tpe)
    val okExpr = fromWireExpr(tpe, "exec.val")
    s"""function $fn(exec) {
       |  switch (exec.tag) {
       |    case "ok":
       |      return { tag: "ok", val: $okExpr };
       |    default:
       |      return exec;
       |  }
       |}
       |""".stripMargin
  }

  private def fromWireExpr(tpe: AbiType, expr: String): String = tpe match {
    case AbiType.List(elm) =>
      s"Array.from($expr, (x) => ${fromWireExpr(elm, "x")})"
    case AbiType.Array(elm) =>
      s"Array.from($expr, (x) => ${fromWireExpr(elm, "x")})"
    case AbiType.Tuple(elms) =>
      s"[${elms.zipWithIndex.map { case (elm, idx) => fromWireExpr(elm, s"$expr.f$idx") }.mkString(", ")}]"
    case AbiType.Record(fields) =>
      jsObjectExpr(fields.map { case (label, fieldTpe) => jsObjectField(label, fromWireExpr(fieldTpe, jsPropAccess(expr, label))) }.mkString(", "))
    case AbiType.Option(elm) =>
      s"($expr.isSome ? ${fromWireExpr(elm, s"$expr.val")} : null)"
    case AbiType.Result(ok, err) =>
      s"($expr.isOk ? ${jsObjectExpr(s"""tag: "ok", val: ${fromWireExpr(ok, s"$expr.ok")}""")} : ${jsObjectExpr(s"""tag: "err", val: ${fromWireExpr(err, s"$expr.err")}""")})"
    case _ => expr
  }

  private def defaultJsExpr(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "undefined"
    case AbiType.Bool => "false"
    case AbiType.Int8 | AbiType.Int16 | AbiType.Int32 | AbiType.Float32 | AbiType.Float64 => "0"
    case AbiType.Int64 => "0n"
    case AbiType.String => "\"\""
    case AbiType.Bytes => "new Uint8Array()"
    case AbiType.List(_) | AbiType.Array(_) => "[]"
    case AbiType.Tuple(elms) =>
      s"{ ${elms.zipWithIndex.map { case (elm, idx) => s"f$idx: ${defaultJsExpr(elm)}" }.mkString(", ")} }"
    case AbiType.Record(fields) =>
      fields.map { case (label, fieldTpe) => jsObjectField(label, defaultJsExpr(fieldTpe)) }.mkString("{ ", ", ", " }")
    case AbiType.Option(elm) =>
      s"{ isSome: false, val: ${defaultJsExpr(elm)} }"
    case AbiType.Result(ok, err) =>
      s"{ isOk: true, ok: ${defaultJsExpr(ok)}, err: ${defaultJsExpr(err)} }"
  }

  private def fromExecExpr(resultTpe: AbiType, expr: String): String =
    if (ExportAbi.isAggregate(resultTpe)) s"${jsExecHelperName(resultTpe)}($expr)" else expr

  private def fromRequestExpr(params: List[AbiType], expr: String): String = params match {
    case Nil => "undefined"
    case tpe :: Nil => fromWireExpr(tpe, s"$expr.arg0")
    case many =>
      s"[${many.zipWithIndex.map { case (tpe, idx) => fromWireExpr(tpe, s"$expr.arg$idx") }.mkString(", ")}]"
  }

  private def toWireExpr(tpe: AbiType, expr: String, nested: Boolean): String = tpe match {
    case AbiType.List(elm) =>
      s"Array.from($expr, (x) => ${toWireExpr(elm, "x", nested = true)})"
    case AbiType.Array(elm) =>
      s"Array.from($expr, (x) => ${toWireExpr(elm, "x", nested = true)})"
    case AbiType.Tuple(elms) =>
      jsObjectExpr(elms.zipWithIndex.map { case (elm, idx) => s"f$idx: ${toWireExpr(elm, s"$expr[$idx]", nested = true)}" }.mkString(", "))
    case AbiType.Record(fields) =>
      jsObjectExpr(fields.map { case (label, fieldTpe) => jsObjectField(label, toWireExpr(fieldTpe, jsPropAccess(expr, label), nested = true)) }.mkString(", "))
    case AbiType.Option(elm) =>
      s"($expr === null ? ${jsObjectExpr(s"isSome: false, val: ${defaultJsExpr(elm)}")} : ${jsObjectExpr(s"isSome: true, val: ${toWireExpr(elm, expr, nested = true)}")})"
    case AbiType.Result(ok, err) =>
      s"($expr.tag === \"ok\" ? ${jsObjectExpr(s"isOk: true, ok: ${toWireExpr(ok, s"$expr.val", nested = true)}, err: ${defaultJsExpr(err)}")} : ${jsObjectExpr(s"isOk: false, ok: ${defaultJsExpr(ok)}, err: ${toWireExpr(err, s"$expr.val", nested = true)}")})"
    case t if ExportAbi.isAggregate(t) => s"${jsToWireHelperName(t)}($expr)"
    case _ => expr
  }

  private def toWireExpr(tpe: AbiType, expr: String): String =
    toWireExpr(tpe, expr, nested = false)

  private def jsToWireHelperName(tpe: AbiType): String =
    s"to_${jsTypeTag(tpe)}"

  private def jsFromWireHelperName(tpe: AbiType): String =
    s"from_${jsTypeTag(tpe)}"

  private def jsDefaultHelperName(tpe: AbiType): String =
    s"default_${jsTypeTag(tpe)}"

  private def jsExecHelperName(tpe: AbiType): String =
    s"from_exec_${jsTypeTag(tpe)}"

  private def tsRequestTypeOf(params: List[AbiType]): String = params match {
    case Nil => "void"
    case tpe :: Nil => tsTypeOf(tpe)
    case many => s"readonly [${many.map(tsTypeOf).mkString(", ")}]"
  }

  private def jsTypeTag(tpe: AbiType): String =
    tpe.stableId.replace('-', '_')

  private def tsFieldName(label: String): String =
    if (isJsIdentifier(label)) label else s""""$label""""

  private def jsObjectField(label: String, valueExpr: String): String =
    if (isJsIdentifier(label)) s"$label: $valueExpr" else s""""$label": $valueExpr"""

  private def jsPropAccess(expr: String, label: String): String =
    if (isJsIdentifier(label)) s"$expr.$label" else s"""$expr[${quoteJs(label)}]"""

  private def quoteJs(s: String): String =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  private def jsObjectExpr(body: String): String =
    s"({ $body })"

  private def isJsIdentifier(s: String): Boolean =
    s.matches("[A-Za-z_$][A-Za-z0-9_$]*")

  private sealed trait ExportTree
  private case class ExportBranch(children: mutable.LinkedHashMap[String, ExportTree]) extends ExportTree
  private case class ExportLeaf(fnName: String) extends ExportTree

  private def buildTree(exports: List[LlvmWasmTypedExportsWriter.Entry]): ExportBranch = {
    val root = ExportBranch(mutable.LinkedHashMap.empty)

    exports.foreach { e =>
      val segments = symbolSegments(e.symbol)
      putLeaf(root, segments, ExportLeaf(flatFunctionName(e.symbol)))
      val resumeSegments = segments.init ::: List(s"resume${capitalize(segments.last)}")
      putLeaf(root, resumeSegments, ExportLeaf(flatResumeFunctionName(e.symbol)))
      e.requestSignature.foreach { _ =>
        val requestSegments = segments.init ::: List(s"request${capitalize(segments.last)}")
        putLeaf(root, requestSegments, ExportLeaf(flatRequestFunctionName(e.symbol)))
      }
    }

    root
  }

  private def putLeaf(root: ExportBranch, segments: List[String], leaf: ExportLeaf): Unit = {
    var current = root
    segments.init.foreach { seg =>
      val next = current.children.getOrElseUpdate(seg, ExportBranch(mutable.LinkedHashMap.empty))
      current = next match {
        case branch: ExportBranch => branch
        case _: ExportLeaf =>
          throw InternalCompilerException(s"Invalid export symbol hierarchy for '${segments.mkString(".")}'.", ca.uwaterloo.flix.language.ast.SourceLocation.Unknown)
      }
    }
    current.children.put(segments.last, leaf)
  }

  private def renderTree(root: ExportBranch, renderLeaf: ExportLeaf => String): String = {
    def loop(branch: ExportBranch): String = {
      val body = branch.children.iterator.map {
        case (name, next: ExportBranch) =>
          s"${renderJsProperty(name)}: ${loop(next)}"
        case (name, leaf: ExportLeaf) =>
          s"${renderJsProperty(name)}: ${renderLeaf(leaf)}"
      }.mkString(", ")
      s"{ $body }"
    }

    loop(root)
  }

  private def flatFunctionName(sym: String): String =
    s"call_${mangleIdentifier(sym.replace('.', '_'))}"

  private def flatResumeFunctionName(sym: String): String =
    s"resume_${mangleIdentifier(sym.replace('.', '_'))}"

  private def flatRequestFunctionName(sym: String): String =
    s"request_${mangleIdentifier(sym.replace('.', '_'))}"

  private def symbolSegments(sym: String): List[String] =
    sym.split("\\.").toList.filter(_.nonEmpty)

  private def renderJsProperty(name: String): String =
    if (isValidJsIdentifier(name)) name else "\"" + escapeJsString(name) + "\""

  private def renderJsString(s: String): String =
    "\"" + escapeJsString(s) + "\""

  private def isValidJsIdentifier(s: String): Boolean =
    s.nonEmpty &&
      (s.head == '_' || s.head == '$' || s.head.isLetter) &&
      s.tail.forall(ch => ch == '_' || ch == '$' || ch.isLetterOrDigit)

  private def mangleIdentifier(s: String): String = {
    val b = new StringBuilder(s.length + 8)
    s.foreach {
      case c if c.isLetterOrDigit || c == '_' || c == '$' => b.append(c)
      case _ => b.append('_')
    }
    if (b.isEmpty) "_"
    else {
      val head = b.charAt(0)
      if (head.isDigit) "_" + b.toString() else b.toString()
    }
  }

  private def jsMethodNameFromWitName(name: String): String =
    WasmImportInterface.jsName(name)

  private def capitalize(s: String): String =
    if (s.isEmpty) s else s"${s.head.toUpper}${s.tail}"

  private def escapeJsString(s: String): String = {
    val b = new StringBuilder(s.length + 8)
    s.foreach {
      case '"' => b.append("\\\"")
      case '\\' => b.append("\\\\")
      case '\b' => b.append("\\b")
      case '\f' => b.append("\\f")
      case '\n' => b.append("\\n")
      case '\r' => b.append("\\r")
      case '\t' => b.append("\\t")
      case c if c < ' ' => b.append(f"\\u${c.toInt}%04x")
      case c => b.append(c)
    }
    b.toString()
  }

  private def writeFile(path: Path, bytes: Array[Byte]): Unit = {
    Files.createDirectories(path.getParent)

    if (Files.exists(path)) {
      if (!Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
        throw InternalCompilerException(s"Unable to write to non-regular file: '$path'.", ca.uwaterloo.flix.language.ast.SourceLocation.Unknown)
      }
      if (!Files.isWritable(path)) {
        throw InternalCompilerException(s"Unable to write to read-only file: '$path'.", ca.uwaterloo.flix.language.ast.SourceLocation.Unknown)
      }
    }

    Files.write(path, bytes)
  }
}
