def f() : Int = {

  //let x = [1,2,3];
  //length[x]
  /* Array */
  // [1,2,3,4,5] // (ArrayLit)
  // [10;g()] // (ArrayNew)
  // 2[10] // ((ArrayLoad)
  // 2[2] = 2 // (ArrayStore)
  // length[2] // (ArrayLength)
  // 2[2..2] // (ArraySlice)
  // 2[2..] // (ArraySliceNoEndIndex)
  // 2[..2] // (ArraySliceNoStartIndex)

  /* Vector */
  //[|1, 1, 1, 1, 1|]
  //[|1;5|]
  let y = [|1, 2|];
  y[|1|]
  //Vlength[|1|]

}
 //def g() : 47 = 47


