/**
 * The ParitySign lattice is the reduced product of the Parity and Sign lattices.
 */
namespace ParitySign {

    /**
     * The elements of the Parity lattice.
     */
    enum Parity {

    }

    /**
     * The elements of the Sign lattice.
     */
    enum Sign {

    }

    /**
     * The Cartesian product of the two lattices.
     */
    enum ParitySign {

    }


    def leq(x: ParitySign, y: ParitySign): Bool = ???

    // TODO: Chain??

    // See other wikipedia examples.


}