[package]
name        = "weather"
description = "show the weather in your current position"
version     = "0.1.0"
flix        = "0.58.1"
authors     = ["Chenhao Gao <chenhaogao123@gmail.com>"]

[dependencies]
"github:mlutze/flix-json" =  "0.12.17"
