[package]
name        = "hello-world"                     # The name of the package.
description = "A simple program"                # The description of the package.
version     = "0.1.0"                           # The semantic version of the package.
flix        = "0.33.0"                          # The required version of the Flix compiler.
license     = "Apache-2.0"                      # The license applicable to this project (see also LICENSE.md).
authors     = ["John Doe <john@example.com"]    # The authors of this project.

[dependencies]                                  # Dependencies on Flix packages.
"github:jls/tic-tac-toe" = "1.2.3"
"github:mlutze/flixball" = "1.2.3"

[dev-dependencies]                              # Development dependencies on Flix packages.
"github:fuzzer/fuzzer" = "1.2.3"

[mvn-dependencies]                              # Dependencies on Maven packages.
"org.postgresql:postgresql"      = "1.2.3"
"org.eclipse.jetty:jetty-server" = "1.2.3"

[dev-mvn-dependencies]                          # Development dependencies on Maven packages.
"org.junit:junit"                = "1.2.3"
