/*
 * Copyright 2024 Magnus Madsen
 *
 * Use of this source code is governed by the Apache 2.0 license
 * that can be found in the LICENSE.md file.
 */
package ca.uwaterloo.flix.api

import ca.uwaterloo.flix.language.ast.Symbol
import ca.uwaterloo.flix.language.phase.typer.TypeConstraint
import ca.uwaterloo.flix.language.phase.unification.set.Equation

/**
  * A common super-type for Flix events.
  */
sealed trait FlixEvent

object FlixEvent {

  /**
    * An event that is fired each time the JVM backend emits a class file for `sym`. `bytes` is
    * the length of the generated bytecode. A single source-level def may produce several events
    * (e.g. function class + closure classes).
    */
  case class EmittedClass(sym: Symbol.DefnSym, bytes: Int) extends FlixEvent

  /**
    * An event that is fired each time the inliner replaces a call site of `sym` with the def's body.
    * `sym` is the callee being inlined.
    */
  case class InlinedDef(sym: Symbol.DefnSym) extends FlixEvent

  /**
    * An event that is fired when new type constraints are collected for the given def symbol `sym`.
    */
  case class NewConstraintsDef(sym: Symbol.DefnSym, tconstrs: List[TypeConstraint]) extends FlixEvent

  /**
   * An event that is fired when a new system of Boolean equation is about to be solved.
   */
  case class SolveEffEquations(econstrs: List[Equation]) extends FlixEvent

}
