/*
 * Copyright 2025 Magnus Madsen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix.api

import ca.uwaterloo.flix.util.LocalResource

object Library {

  /**
    * A sequence of internal inputs to be parsed into Flix ASTs.
    *
    * The core library *must* be present for any program to compile.
    */
  val CoreLibrary: List[(String, String)] = List(
    "Add.flix" -> LocalResource.get("/src/library/Add.flix"),
    "Bool.flix" -> LocalResource.get("/src/library/Bool.flix"),
    "Coerce.flix" -> LocalResource.get("/src/library/Coerce.flix"),
    "Comparison.flix" -> LocalResource.get("/src/library/Comparison.flix"),
    "Div.flix" -> LocalResource.get("/src/library/Div.flix"),
    "Eq.flix" -> LocalResource.get("/src/library/Eq.flix"),
    "Hash.flix" -> LocalResource.get("/src/library/Hash.flix"),
    "JoinLattice.flix" -> LocalResource.get("/src/library/JoinLattice.flix"),
    "LowerBound.flix" -> LocalResource.get("/src/library/LowerBound.flix"),
    "MeetLattice.flix" -> LocalResource.get("/src/library/MeetLattice.flix"),
    "Mul.flix" -> LocalResource.get("/src/library/Mul.flix"),
    "Neg.flix" -> LocalResource.get("/src/library/Neg.flix"),
    "Order.flix" -> LocalResource.get("/src/library/Order.flix"),
    "PartialOrder.flix" -> LocalResource.get("/src/library/PartialOrder.flix"),
    "Prelude.flix" -> LocalResource.get("/src/library/Prelude.flix"),
    "Ref.flix" -> LocalResource.get("/src/library/Ref.flix"),
    "Reflect.flix" -> LocalResource.get("/src/library/Reflect.flix"),
    "Sub.flix" -> LocalResource.get("/src/library/Sub.flix"),
    "ToString.flix" -> LocalResource.get("/src/library/ToString.flix"),
    "UpperBound.flix" -> LocalResource.get("/src/library/UpperBound.flix"),
  )

  /**
    * A sequence of internal inputs to be parsed into Flix ASTs.
    *
    * The standard library is not required to be present for at least some programs to compile.
    */
  val StandardLibrary: List[(String, String)] = List(
    "Abort.flix" -> LocalResource.get("/src/library/Abort.flix"),
    "Adaptor.flix" -> LocalResource.get("/src/library/Adaptor.flix"),
    "Applicative.flix" -> LocalResource.get("/src/library/Applicative.flix"),
    "Array.flix" -> LocalResource.get("/src/library/Array.flix"),
    "Assert.flix" -> LocalResource.get("/src/library/Assert.flix"),
    "BigDecimal.flix" -> LocalResource.get("/src/library/BigDecimal.flix"),
    "BigInt.flix" -> LocalResource.get("/src/library/BigInt.flix"),
    "Box.flix" -> LocalResource.get("/src/library/Box.flix"),
    "BPlusTree.flix" -> LocalResource.get("/src/library/BPlusTree.flix"),
    "BPlusTree/AtomicCounter.flix" -> LocalResource.get("/src/library/BPlusTree/AtomicCounter.flix"),
    "BPlusTree/Lock.flix" -> LocalResource.get("/src/library/BPlusTree/Lock.flix"),
    "BPlusTree/Node.flix" -> LocalResource.get("/src/library/BPlusTree/Node.flix"),
    "BufReader.flix" -> LocalResource.get("/src/library/BufReader.flix"),
    "Chain.flix" -> LocalResource.get("/src/library/Chain.flix"),
    "Channel.flix" -> LocalResource.get("/src/library/Channel.flix"),
    "Codec.flix" -> LocalResource.get("/src/library/Codec.flix"),
    "Checksum.flix" -> LocalResource.get("/src/library/Checksum.flix"),
    "Char.flix" -> LocalResource.get("/src/library/Char.flix"),
    "CharacterSet.flix" -> LocalResource.get("/src/library/CharacterSet.flix"),
    "CodePoint.flix" -> LocalResource.get("/src/library/CodePoint.flix"),
    "Collectable.flix" -> LocalResource.get("/src/library/Collectable.flix"),
    "CommutativeGroup.flix" -> LocalResource.get("/src/library/CommutativeGroup.flix"),
    "CommutativeMonoid.flix" -> LocalResource.get("/src/library/CommutativeMonoid.flix"),
    "CommutativeSemiGroup.flix" -> LocalResource.get("/src/library/CommutativeSemiGroup.flix"),
    "Concurrent.flix" -> LocalResource.get("/src/library/Concurrent.flix"),
    "Concurrent/Channel.flix" -> LocalResource.get("/src/library/Concurrent/Channel.flix"),
    "Concurrent/Condition.flix" -> LocalResource.get("/src/library/Concurrent/Condition.flix"),
    "Concurrent/CyclicBarrier.flix" -> LocalResource.get("/src/library/Concurrent/CyclicBarrier.flix"),
    "Concurrent/ReentrantLock.flix" -> LocalResource.get("/src/library/Concurrent/ReentrantLock.flix"),
    "Sys/Console.flix" -> LocalResource.get("/src/library/Sys/Console.flix"),
    "Debug.flix" -> LocalResource.get("/src/library/Debug.flix"),
    "DecodingReader.flix" -> LocalResource.get("/src/library/DecodingReader.flix"),
    "DelayList.flix" -> LocalResource.get("/src/library/DelayList.flix"),
    "DelayMap.flix" -> LocalResource.get("/src/library/DelayMap.flix"),
    "Discrete.flix" -> LocalResource.get("/src/library/Discrete.flix"),
    "Down.flix" -> LocalResource.get("/src/library/Down.flix"),
    "EncodingWriter.flix" -> LocalResource.get("/src/library/EncodingWriter.flix"),
    "Filterable.flix" -> LocalResource.get("/src/library/Filterable.flix"),
    "Fs.flix" -> LocalResource.get("/src/library/Fs.flix"),
    "Fs/AccessTime.flix" -> LocalResource.get("/src/library/Fs/AccessTime.flix"),
    "Fs/CreationTime.flix" -> LocalResource.get("/src/library/Fs/CreationTime.flix"),
    "Fs/CopyFile.flix" -> LocalResource.get("/src/library/Fs/CopyFile.flix"),
    "Fs/CopyOption.flix" -> LocalResource.get("/src/library/Fs/CopyOption.flix"),
    "Fs/DeleteFile.flix" -> LocalResource.get("/src/library/Fs/DeleteFile.flix"),
    "Fs/DirList.flix" -> LocalResource.get("/src/library/Fs/DirList.flix"),
    "Fs/Glob.flix" -> LocalResource.get("/src/library/Fs/Glob.flix"),
    "Fs/FsLayer.flix" -> LocalResource.get("/src/library/Fs/FsLayer.flix"),
    "Fs/FileExists.flix" -> LocalResource.get("/src/library/Fs/FileExists.flix"),
    "Fs/FilePermission.flix" -> LocalResource.get("/src/library/Fs/FilePermission.flix"),
    "Fs/FileRead.flix" -> LocalResource.get("/src/library/Fs/FileRead.flix"),
    "Fs/FileSize.flix" -> LocalResource.get("/src/library/Fs/FileSize.flix"),
    "Fs/Size.flix" -> LocalResource.get("/src/library/Fs/Size.flix"),
    "Fs/SizeUnit.flix" -> LocalResource.get("/src/library/Fs/SizeUnit.flix"),
    "Fs/FileStat.flix" -> LocalResource.get("/src/library/Fs/FileStat.flix"),
    "Fs/FileSystem.flix" -> LocalResource.get("/src/library/Fs/FileSystem.flix"),
    "Fs/FileTest.flix" -> LocalResource.get("/src/library/Fs/FileTest.flix"),
    "Fs/FileWrite.flix" -> LocalResource.get("/src/library/Fs/FileWrite.flix"),
    "Fs/FileTime.flix" -> LocalResource.get("/src/library/Fs/FileTime.flix"),
    "Fs/IsDirectory.flix" -> LocalResource.get("/src/library/Fs/IsDirectory.flix"),
    "Fs/IsExecutable.flix" -> LocalResource.get("/src/library/Fs/IsExecutable.flix"),
    "Fs/IsReadable.flix" -> LocalResource.get("/src/library/Fs/IsReadable.flix"),
    "Fs/IsRegularFile.flix" -> LocalResource.get("/src/library/Fs/IsRegularFile.flix"),
    "Fs/IsSymbolicLink.flix" -> LocalResource.get("/src/library/Fs/IsSymbolicLink.flix"),
    "Fs/IsWritable.flix" -> LocalResource.get("/src/library/Fs/IsWritable.flix"),
    "Fs/ModificationTime.flix" -> LocalResource.get("/src/library/Fs/ModificationTime.flix"),
    "Fs/InMemoryFs.flix" -> LocalResource.get("/src/library/Fs/InMemoryFs.flix"),
    "Fs/MemoryOverlay.flix" -> LocalResource.get("/src/library/Fs/MemoryOverlay.flix"),
    "Fs/ReadBytes.flix" -> LocalResource.get("/src/library/Fs/ReadBytes.flix"),
    "Fs/ReadFile.flix" -> LocalResource.get("/src/library/Fs/ReadFile.flix"),
    "Fs/ReadLines.flix" -> LocalResource.get("/src/library/Fs/ReadLines.flix"),
    "Fs/Truncate.flix" -> LocalResource.get("/src/library/Fs/Truncate.flix"),
    "Fs/WriteBytes.flix" -> LocalResource.get("/src/library/Fs/WriteBytes.flix"),
    "Fs/WriteFile.flix" -> LocalResource.get("/src/library/Fs/WriteFile.flix"),
    "Fs/WriteLines.flix" -> LocalResource.get("/src/library/Fs/WriteLines.flix"),
    "Fs/AppendBytes.flix" -> LocalResource.get("/src/library/Fs/AppendBytes.flix"),
    "Fs/AppendFile.flix" -> LocalResource.get("/src/library/Fs/AppendFile.flix"),
    "Fs/AppendLines.flix" -> LocalResource.get("/src/library/Fs/AppendLines.flix"),
    "Fs/MkDir.flix" -> LocalResource.get("/src/library/Fs/MkDir.flix"),
    "Fs/MkDirs.flix" -> LocalResource.get("/src/library/Fs/MkDirs.flix"),
    "Fs/MkTempDir.flix" -> LocalResource.get("/src/library/Fs/MkTempDir.flix"),
    "Fs/MoveFile.flix" -> LocalResource.get("/src/library/Fs/MoveFile.flix"),
    "Fs/MoveOption.flix" -> LocalResource.get("/src/library/Fs/MoveOption.flix"),
    "Fixpoint3.flix" -> LocalResource.get("/src/library/Fixpoint3.flix"),
    "Fixpoint3/Ast.flix" -> LocalResource.get("/src/library/Fixpoint3/Ast.flix"),
    "Fixpoint3/Ast/Datalog.flix" -> LocalResource.get("/src/library/Fixpoint3/Ast/Datalog.flix"),
    "Fixpoint3/Ast/ExecutableRam.flix" -> LocalResource.get("/src/library/Fixpoint3/Ast/ExecutableRam.flix"),
    "Fixpoint3/Ast/Ram.flix" -> LocalResource.get("/src/library/Fixpoint3/Ast/Ram.flix"),
    "Fixpoint3/Ast/Shared.flix" -> LocalResource.get("/src/library/Fixpoint3/Ast/Shared.flix"),
    "Fixpoint3/Boxable.flix" -> LocalResource.get("/src/library/Fixpoint3/Boxable.flix"),
    "Fixpoint3/Boxing.flix" -> LocalResource.get("/src/library/Fixpoint3/Boxing.flix"),
    "Fixpoint3/BoxingType.flix" -> LocalResource.get("/src/library/Fixpoint3/BoxingType.flix"),
    "Fixpoint3/Counter.flix" -> LocalResource.get("/src/library/Fixpoint3/Counter.flix"),
    "Fixpoint3/Debugging.flix" -> LocalResource.get("/src/library/Fixpoint3/Debugging.flix"),
    "Fixpoint3/Interpreter.flix" -> LocalResource.get("/src/library/Fixpoint3/Interpreter.flix"),
    "Fixpoint3/Options.flix" -> LocalResource.get("/src/library/Fixpoint3/Options.flix"),
    "Fixpoint3/Phase.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase.flix"),
    "Fixpoint3/Phase/Compiler.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/Compiler.flix"),
    "Fixpoint3/Phase/Hoisting.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/Hoisting.flix"),
    "Fixpoint3/Phase/IndexSelection.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/IndexSelection.flix"),
    "Fixpoint3/Phase/IndexSelection/AutomaticIndexSelection.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/IndexSelection/AutomaticIndexSelection.flix"),
    "Fixpoint3/Phase/Lowering.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/Lowering.flix"),
    "Fixpoint3/Phase/ProvenanceAugment.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/ProvenanceAugment.flix"),
    "Fixpoint3/Phase/RenamePredSyms.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/RenamePredSyms.flix"),
    "Fixpoint3/Phase/Simplifier.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/Simplifier.flix"),
    "Fixpoint3/Phase/Stratifier.flix" -> LocalResource.get("/src/library/Fixpoint3/Phase/Stratifier.flix"),
    "Fixpoint3/PrecedenceGraph.flix" -> LocalResource.get("/src/library/Fixpoint3/PrecedenceGraph.flix"),
    "Fixpoint3/PrecedenceGraph/MutGraph.flix" -> LocalResource.get("/src/library/Fixpoint3/PrecedenceGraph/MutGraph.flix"),
    "Fixpoint3/Predicate.flix" -> LocalResource.get("/src/library/Fixpoint3/Predicate.flix"),
    "Fixpoint3/ProvenanceReconstruct.flix" -> LocalResource.get("/src/library/Fixpoint3/ProvenanceReconstruct.flix"),
    "Fixpoint3/ProvenanceReconstruct/ProofTree.flix" -> LocalResource.get("/src/library/Fixpoint3/ProvenanceReconstruct/ProofTree.flix"),
    "Fixpoint3/ReadWriteLock.flix" -> LocalResource.get("/src/library/Fixpoint3/ReadWriteLock.flix"),
    "Fixpoint3/Solver.flix" -> LocalResource.get("/src/library/Fixpoint3/Solver.flix"),
    "Fixpoint3/TypeInfo.flix" -> LocalResource.get("/src/library/Fixpoint3/TypeInfo.flix"),
    "Fixpoint3/UniqueInts.flix" -> LocalResource.get("/src/library/Fixpoint3/UniqueInts.flix"),
    "Fixpoint3/Util.flix" -> LocalResource.get("/src/library/Fixpoint3/Util.flix"),
    "Float32.flix" -> LocalResource.get("/src/library/Float32.flix"),
    "Float64.flix" -> LocalResource.get("/src/library/Float64.flix"),
    "Foldable.flix" -> LocalResource.get("/src/library/Foldable.flix"),
    "ForEach.flix" -> LocalResource.get("/src/library/ForEach.flix"),
    "Formattable.flix" -> LocalResource.get("/src/library/Formattable.flix"),
    "FromString.flix" -> LocalResource.get("/src/library/FromString.flix"),
    "Functor.flix" -> LocalResource.get("/src/library/Functor.flix"),
    "GetOpt.flix" -> LocalResource.get("/src/library/GetOpt.flix"),
    "Graph.flix" -> LocalResource.get("/src/library/Graph.flix"),
    "Group.flix" -> LocalResource.get("/src/library/Group.flix"),
    "Identity.flix" -> LocalResource.get("/src/library/Identity.flix"),
    "Indexable.flix" -> LocalResource.get("/src/library/Indexable.flix"),
    "IndexableMut.flix" -> LocalResource.get("/src/library/IndexableMut.flix"),
    "Int16.flix" -> LocalResource.get("/src/library/Int16.flix"),
    "Int32.flix" -> LocalResource.get("/src/library/Int32.flix"),
    "Int64.flix" -> LocalResource.get("/src/library/Int64.flix"),
    "Int8.flix" -> LocalResource.get("/src/library/Int8.flix"),
    "IoError.flix" -> LocalResource.get("/src/library/IoError.flix"),
    "Iterable.flix" -> LocalResource.get("/src/library/Iterable.flix"),
    "Iterator.flix" -> LocalResource.get("/src/library/Iterator.flix"),
    "KeyNotFound.flix" -> LocalResource.get("/src/library/KeyNotFound.flix"),
    "List.flix" -> LocalResource.get("/src/library/List.flix"),
    "Logger.flix" -> LocalResource.get("/src/library/Logger.flix"),
    "Map.flix" -> LocalResource.get("/src/library/Map.flix"),
    "Monad.flix" -> LocalResource.get("/src/library/Monad.flix"),
    "MonadZero.flix" -> LocalResource.get("/src/library/MonadZero.flix"),
    "MonadZip.flix" -> LocalResource.get("/src/library/MonadZip.flix"),
    "Monoid.flix" -> LocalResource.get("/src/library/Monoid.flix"),
    "MultiMap.flix" -> LocalResource.get("/src/library/MultiMap.flix"),
    "MutDeque.flix" -> LocalResource.get("/src/library/MutDeque.flix"),
    "MutDisjointSets.flix" -> LocalResource.get("/src/library/MutDisjointSets.flix"),
    "MutHashMap.flix" -> LocalResource.get("/src/library/MutHashMap.flix"),
    "MutHashSet.flix" -> LocalResource.get("/src/library/MutHashSet.flix"),
    "MutList.flix" -> LocalResource.get("/src/library/MutList.flix"),
    "MutMap.flix" -> LocalResource.get("/src/library/MutMap.flix"),
    "MutPriorityQueue.flix" -> LocalResource.get("/src/library/MutPriorityQueue.flix"),
    "MutSet.flix" -> LocalResource.get("/src/library/MutSet.flix"),
    "Net.flix" -> LocalResource.get("/src/library/Net.flix"),
    "Net/Body.flix" -> LocalResource.get("/src/library/Net/Body.flix"),
    "Net/Dns.flix" -> LocalResource.get("/src/library/Net/Dns.flix"),
    "Net/IpAddr.flix" -> LocalResource.get("/src/library/Net/IpAddr.flix"),
    "Net/Ipv4Addr.flix" -> LocalResource.get("/src/library/Net/Ipv4Addr.flix"),
    "Net/Ipv6Addr.flix" -> LocalResource.get("/src/library/Net/Ipv6Addr.flix"),
    "Net/Http.flix" -> LocalResource.get("/src/library/Net/Http.flix"),
    "Net/HttpLayer.flix" -> LocalResource.get("/src/library/Net/HttpLayer.flix"),
    "Net/Https.flix" -> LocalResource.get("/src/library/Net/Https.flix"),
    "Net/HttpRequest.flix" -> LocalResource.get("/src/library/Net/HttpRequest.flix"),
    "Net/HttpResponse.flix" -> LocalResource.get("/src/library/Net/HttpResponse.flix"),
    "Net/Method.flix" -> LocalResource.get("/src/library/Net/Method.flix"),
    "Net/Ping.flix" -> LocalResource.get("/src/library/Net/Ping.flix"),
    "Net/Retry.flix" -> LocalResource.get("/src/library/Net/Retry.flix"),
    "Net/RetryDecision.flix" -> LocalResource.get("/src/library/Net/RetryDecision.flix"),
    "Net/RetryOutcome.flix" -> LocalResource.get("/src/library/Net/RetryOutcome.flix"),
    "Net/SocketAddr.flix" -> LocalResource.get("/src/library/Net/SocketAddr.flix"),
    "Net/SocketAddrV4.flix" -> LocalResource.get("/src/library/Net/SocketAddrV4.flix"),
    "Net/SocketAddrV6.flix" -> LocalResource.get("/src/library/Net/SocketAddrV6.flix"),
    "Net/TcpAccept.flix" -> LocalResource.get("/src/library/Net/TcpAccept.flix"),
    "Net/TcpBind.flix" -> LocalResource.get("/src/library/Net/TcpBind.flix"),
    "Net/TcpConnect.flix" -> LocalResource.get("/src/library/Net/TcpConnect.flix"),
    "Net/TcpServer.flix" -> LocalResource.get("/src/library/Net/TcpServer.flix"),
    "Net/TcpSocket.flix" -> LocalResource.get("/src/library/Net/TcpSocket.flix"),
    "Nec.flix" -> LocalResource.get("/src/library/Nec.flix"),
    "Nel.flix" -> LocalResource.get("/src/library/Nel.flix"),
    "Object.flix" -> LocalResource.get("/src/library/Object.flix"),
    "Option.flix" -> LocalResource.get("/src/library/Option.flix"),
    "OutOfBounds.flix" -> LocalResource.get("/src/library/OutOfBounds.flix"),
    "Peekable.flix" -> LocalResource.get("/src/library/Peekable.flix"),
    "Math/Random.flix" -> LocalResource.get("/src/library/Math/Random.flix"),
    "Range.flix" -> LocalResource.get("/src/library/Range.flix"),
    "Readable.flix" -> LocalResource.get("/src/library/Readable.flix"),
    "RedBlackTree.flix" -> LocalResource.get("/src/library/RedBlackTree.flix"),
    "Reducible.flix" -> LocalResource.get("/src/library/Reducible.flix"),
    "Regex.flix" -> LocalResource.get("/src/library/Regex.flix"),
    "Result.flix" -> LocalResource.get("/src/library/Result.flix"),
    "RichString.flix" -> LocalResource.get("/src/library/RichString.flix"),
    "SemiGroup.flix" -> LocalResource.get("/src/library/SemiGroup.flix"),
    "Set.flix" -> LocalResource.get("/src/library/Set.flix"),
    "Math.flix" -> LocalResource.get("/src/library/Math.flix"),
    "Math/Shuffle.flix" -> LocalResource.get("/src/library/Math/Shuffle.flix"),
    "String.flix" -> LocalResource.get("/src/library/String.flix"),
    "StringBuilder.flix" -> LocalResource.get("/src/library/StringBuilder.flix"),
    "Sys.flix" -> LocalResource.get("/src/library/Sys.flix"),
    "Sys/Env.flix" -> LocalResource.get("/src/library/Sys/Env.flix"),
    "Sys/Exit.flix" -> LocalResource.get("/src/library/Sys/Exit.flix"),
    "Sys/Process.flix" -> LocalResource.get("/src/library/Sys/Process.flix"),
    "Sys/ProcessHandle.flix" -> LocalResource.get("/src/library/Sys/ProcessHandle.flix"),
    "Sys/StdErr.flix" -> LocalResource.get("/src/library/Sys/StdErr.flix"),
    "Sys/StdIn.flix" -> LocalResource.get("/src/library/Sys/StdIn.flix"),
    "Sys/StdOut.flix" -> LocalResource.get("/src/library/Sys/StdOut.flix"),
    "Time.flix" -> LocalResource.get("/src/library/Time.flix"),
    "Time/Clock.flix" -> LocalResource.get("/src/library/Time/Clock.flix"),
    "Time/Duration.flix" -> LocalResource.get("/src/library/Time/Duration.flix"),
    "Time/Sleep.flix" -> LocalResource.get("/src/library/Time/Sleep.flix"),
    "Time/TimeUnit.flix" -> LocalResource.get("/src/library/Time/TimeUnit.flix"),
    "ToFlix.flix" -> LocalResource.get("/src/library/ToFlix.flix"),
    "ToJava.flix" -> LocalResource.get("/src/library/ToJava.flix"),
    "Traversable.flix" -> LocalResource.get("/src/library/Traversable.flix"),
    "UnorderedFoldable.flix" -> LocalResource.get("/src/library/UnorderedFoldable.flix"),
    "Validation.flix" -> LocalResource.get("/src/library/Validation.flix"),
    "Vector.flix" -> LocalResource.get("/src/library/Vector.flix"),
    "Witherable.flix" -> LocalResource.get("/src/library/Witherable.flix"),
    "Writable.flix" -> LocalResource.get("/src/library/Writable.flix"),
  )

}
