[package]
version = "0.1.0"                               # The semantic version of the package.
flix    = "0.75.3"                              # The required version of the Flix compiler.

[dependencies]                                  # Dependencies on Flix packages.
"github:flix/museum"              = "1.1.0"
"github:magnus-madsen/helloworld" = "1.3.0"

[mvn-dependencies]                              # Dependencies on Maven packages.
"org.junit.jupiter:junit-jupiter-api" = "5.9.2"
