[package]
name = "example-flix-project"
version = "1.2.3"
flix = "0.31.0"

[package.dependencies]
mvn."org.postgresql:postgresql" = "42.3.3"
mvn."org.eclipse.jetty:jetty-server" = "11.0.11"
fpkg."com.github.paulbutcher/my-flix-library" = "0.3.1"

[build.dev.dependencies]
fpkg."com.github.example/debugging-helper" = "2.3.4"
