/*
 * Copyright 2026 Flix Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.ast.jvm

import ca.uwaterloo.flix.language.ast.jvm.JavaModifiers.*

/** Class-file metadata that carries access and property flags: a class, a method, or a field. */
trait JavaMember {

  /** The access and property flags of this member (see [[JavaModifiers]]). */
  def modifiers: Int

  def isPublic: Boolean = has(modifiers, ACC_PUBLIC)

  def isPrivate: Boolean = has(modifiers, ACC_PRIVATE)

  def isProtected: Boolean = has(modifiers, ACC_PROTECTED)

  def isStatic: Boolean = has(modifiers, ACC_STATIC)

  def isFinal: Boolean = has(modifiers, ACC_FINAL)

  def isAbstract: Boolean = has(modifiers, ACC_ABSTRACT)

  /** Returns whether this member was generated by the compiler and does not appear in the source code. */
  def isSynthetic: Boolean = has(modifiers, ACC_SYNTHETIC)

}
