/*
 * Copyright 2026 Flix Authors
 *
 * Use of this source code is governed by the Apache 2.0 license
 * that can be found in the LICENSE.md file.
 */
package ca.uwaterloo.flix.language.ast.jvm

/** Class-file metadata for a Java method or constructor. */
case class JavaMethod(
  ref: JavaMethodRef,
  modifiers: Int,
  typeParameters: List[JavaTypeParameter],
  parameterNames: List[String],
  parameterTypes: List[JavaType],
  returnType: JavaType,
  isConstructor: Boolean,
  isVarArgs: Boolean
) extends JavaMember {

  /** Returns whether this method was generated by the compiler to bridge an erased signature. */
  def isBridge: Boolean = JavaModifiers.has(modifiers, JavaModifiers.ACC_BRIDGE)

}
