/*
 * Copyright 2026 Flix Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.ast.jvm

/**
  * The access and property flags of Java class files.
  *
  * The flags apply to classes (JVMS §4.1), fields (JVMS §4.5), and methods (JVMS §4.6). Every flag has the same value
  * as its `java.lang.reflect.Modifier` counterpart, but the object is independent of reflection.
  */
object JavaModifiers {

  /** Declared `public`; accessible from any other class. */
  val ACC_PUBLIC: Int = 0x0001

  /** Declared `private`; accessible only within the declaring class (members only). */
  val ACC_PRIVATE: Int = 0x0002

  /** Declared `protected`; accessible within subclasses and the declaring package (members only). */
  val ACC_PROTECTED: Int = 0x0004

  /** Declared `static`; belongs to the class rather than to an instance (members only). */
  val ACC_STATIC: Int = 0x0008

  /** Declared `final`; a class that cannot be extended, a method that cannot be overridden, or a field assigned once. */
  val ACC_FINAL: Int = 0x0010

  /** A method generated by the compiler to bridge an erased signature (methods only). */
  val ACC_BRIDGE: Int = 0x0040

  /** A method whose last parameter is a variable-arity array (methods only). */
  val ACC_VARARGS: Int = 0x0080

  /** An interface rather than a class (classes only). */
  val ACC_INTERFACE: Int = 0x0200

  /** Declared `abstract`; a class that cannot be instantiated or a method without a body. */
  val ACC_ABSTRACT: Int = 0x0400

  /** A member generated by the compiler that does not appear in the source code. */
  val ACC_SYNTHETIC: Int = 0x1000

  /** An annotation interface (classes only). */
  val ACC_ANNOTATION: Int = 0x2000

  /** Returns whether `modifiers` has the given `flag` set. */
  def has(modifiers: Int, flag: Int): Boolean = (modifiers & flag) != 0

}
