/*
 * Copyright 2026 Flix Authors
 *
 * Use of this source code is governed by the Apache 2.0 license
 * that can be found in the LICENSE.md file.
 */
package ca.uwaterloo.flix.language.ast.jvm

import ca.uwaterloo.flix.language.ast.jvm.JavaModifiers.*

/** Class-file metadata that carries access and property flags: a class, a method, or a field. */
trait JavaMember {

  /** The access and property flags of this member (see [[JavaModifiers]]). */
  def modifiers: Int

  /** Returns whether this member is declared `public`. */
  def isPublic: Boolean = has(modifiers, ACC_PUBLIC)

  /** Returns whether this member is declared `private`. */
  def isPrivate: Boolean = has(modifiers, ACC_PRIVATE)

  /** Returns whether this member is declared `protected`. */
  def isProtected: Boolean = has(modifiers, ACC_PROTECTED)

  /** Returns whether this member is declared `static`. */
  def isStatic: Boolean = has(modifiers, ACC_STATIC)

  /** Returns whether this member is declared `final`. */
  def isFinal: Boolean = has(modifiers, ACC_FINAL)

  /** Returns whether this member is declared `abstract`. */
  def isAbstract: Boolean = has(modifiers, ACC_ABSTRACT)

  /** Returns whether this member was generated by the compiler and does not appear in the source code. */
  def isSynthetic: Boolean = has(modifiers, ACC_SYNTHETIC)

}
