[package]
name    = "minimal-example" # The name of the package.
version = "0.1.0"           # The semantic version of the package.
flix    = "0.33.0"          # The required version of the Flix compiler.
