/*
 * Copyright 2026 Alexander Sommer, Samuel Skovbakke
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.phase.typer

import ca.uwaterloo.flix.api.Flix
import ca.uwaterloo.flix.language.ast.{Kind, RigidityEnv, SourceLocation, Symbol, Type, TypeConstructor}
import ca.uwaterloo.flix.language.ast.shared.EffSymOrRigidVar.{Eff, RigidVar}
import ca.uwaterloo.flix.language.ast.shared.{EffSymOrRigidVar, RegionScope, VarText}
import ca.uwaterloo.flix.language.errors.TypeError
import ca.uwaterloo.flix.language.errors.TypeError.UnhandledEffect
import ca.uwaterloo.flix.language.phase.typer.TypeConstraint.{EffConflicted, Provenance}
import ca.uwaterloo.flix.language.phase.unification.shared.{BoolAlg, BoolSubstitution, BoolUnificationException, CofiniteIntSet, SveAlgorithm}
import ca.uwaterloo.flix.language.phase.unification.zhegalkin.{ZhegalkinAlgebra, ZhegalkinExpr}

import scala.annotation.tailrec
import scala.collection.immutable.Queue
import scala.util.Random

/** Analyzes constraints generated by ConstraintSolver in order to provide code
  * actions, inlay hints and better error messages.
  *
  * This module constructs a directed graph representing effect flow from type
  * constraints and performs breadth-first search to identify specific paths
  * from effect to another effect. This helps generate specific errors that help
  * with diagnosing effect related errors. It generates lists of all paths from
  * some effect flowing into another (conflicting) effect.
  */
object EffectProvenance {

  /**
    * Returns a list of effect conflicts if any are found, or None if no good
    * effect error could be made. A conflict is: a path from an effect to a
    * differing effect. E.g. IO -> ... -> {}. This is the main entry point for
    * effect provenance analysis.
    *
    * @param constrs0
    * the list of type constraints to analyze
    * @return
    * a list of conflicts if conflicts could be found, None otherwise
    */
  def getErrors(constrs0: List[TypeConstraint])(implicit scope: RegionScope, renv: RigidityEnv, flix: Flix): Option[List[EffConflicted]] = {
    implicit val alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]] = new ZhegalkinAlgebra[CofiniteIntSet](CofiniteIntSet.LatticeOps)
    if (isDebug(constrs0)) return None
    val newConstrs = constrs0.flatMap(simplifyConstraint) //.flatMap(visitHandlers(_, constrs0))
    val (sources0, rest) = newConstrs.partition {
      case TypeConstraint.Equality(_, tpe2, prov) => prov match {
        case Provenance.Source(_, eff2, _) => !isFlexible(eff2) && !isPure(eff2)
        case Provenance.ExpectArgument(_, _, _, _, _) => !isFlexible(tpe2) && !isPure(tpe2)
        case Provenance.ExpectType(_, _, _) => true
        case _ => false
      }
      case _ => false
    }
    val sources = filterOutDuplicateSources(sources0)
    val contexts = constrs0.filter {
      case TypeConstraint.Equality(_, _, Provenance.Handler(_, _, _)) => true
      case _ => false
    }.flatMap(visitHandlers(_, constrs0))
    var s = rest.foldLeft(Set.empty[Type]) {
      case (acc, TypeConstraint.Equality(_, _, prov)) => prov match {
        case Provenance.ExpectType(expected, _, _) => if (!isPure(expected)) acc ++ consTypeArgs(expected) else acc
        case Provenance.ExpectEffect(expected, _, _) => if (!isPure(expected)) acc ++ consTypeArgs(expected) else acc
        case _ => acc
      }
      case (acc, _) => acc
    }
    val handledEffs = constrs0.foldLeft(Set.empty[Type])((acc, x) => findHandled(x) ++ acc)
    val res = sources.map(a => (a, initialSub(a, Map.empty))
    ).flatMap {
      case (c, (Left(ze), m)) =>
        val (errs, unused) = findConflictsFromSource(c, constrs0.filterNot(_ == c), ze, m, s, handledEffs, contexts)
        s = unused
        errs
      case (_, (Right(err), _)) => err
      case _ => None
    }
    // check for edge cases where a single constraint has both a sink and a source
    val singles = newConstrs.filterNot(pureSource).flatMap(initialSub(_, Map.empty) match {
      case (Right(effErr), _) => Some(effErr)
      case (Left(_), _) => None
    }).flatten
    // create errors for unhandled effects
    val unused = s.map(x => EffConflicted(TypeError.UnusedEffectInSignature(typeToSym(x).head, x.loc))).toList
    val r = unused ++ res ++ singles
    if (r.isEmpty) None else Some(r)
  }

  /** Reorders the front of the work queue so that sink constraints are processed after non-sinks.
    * If the front element is a sink and the second is not, their positions are swapped.
    */
  private def sortSinks(workQueue: Queue[TypeConstraint]): Queue[TypeConstraint] = {
    if (workQueue.size >= 2) {
      val (tmp, wq1) = workQueue.dequeue
      if (isSink(tmp)) {
        val (newHead, wq2) = wq1.dequeue
        wq2.prepended(tmp).prepended(newHead)
      } else workQueue
    }
    else workQueue
  }

  /**
    * returns a list of all effect types that appears in the given type
    */
  private def consTypeArgs(t: Type): List[Type] = {
    val cons = (x: Type) => x :: Nil
    val concat = (x: List[Type], y: List[Type]) => x ::: y
    deconstructType(t, cons, concat, Nil)
  }

  /** Like [[consTypeArgs]], but skips the right-hand side of `Difference` types.
    * This means subtracted (e.g. handled) effects are excluded from the result.
    */
  private def consUsedTypeArgs(t: Type): List[Type] = t match {
    case Type.Apply(tpe1, tpe2, _) => t.typeConstructor match {
      case Some(TypeConstructor.Difference) => consUsedTypeArgs(t.typeArguments.head)
      case Some(_) => consUsedTypeArgs(tpe1) ::: consUsedTypeArgs(tpe2)
      case None => Nil
    }
    case x => consTypeArgs(x)
  }
  /** Traces effect flow from `initial` through `constrs0` using BFS, generating
    * `EffConflicted` errors for every path that reaches a sink constraint (i.e. a
    * function signature that the accumulated effects violate).
    *
    * The inner helper `doStuffHelper` drives the BFS: it extends the work queue
    * via `findNext`, sorts sinks to the back via `sortSinks`, tries to unify the
    * next constraint with `applySubs`, and calls `mkErrors` when unification fails
    * (indicating a genuine conflict).
    *
    * @param initial     the source constraint that seeds the traversal
    * @param constrs0    the remaining constraints to search through
    * @param initialSub  the starting Zhegalkin substitution derived from `initial`
    * @param idMap       mapping from `Type` to integer ids used in Zhegalkin expressions
    * @param unused      set of effect types not yet accounted for by any path
    * @param handledEffs set of effect types that are handled (subtracted) somewhere
    * @param contexts    handler contexts for generating unhandled-effect errors
    * @return a pair of (list of conflicts found, updated set of unused effects)
    */
  private def findConflictsFromSource(initial: TypeConstraint, constrs0: List[TypeConstraint], initialSub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], idMap: Map[Type, Int], unused: Set[Type], handledEffs: Set[Type], contexts: List[HandlerContext])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (List[EffConflicted], Set[Type]) = {
    var s = unused
    s = initial match {
      case TypeConstraint.Equality(_, tpe2, _) =>
        s.diff(consTypeArgs(tpe2).toSet)
      case _ => s
    }

    def loop(visited: List[TypeConstraint], unvisited: List[TypeConstraint], workQueue: Queue[TypeConstraint], sub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], m: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): List[EffConflicted] = {
      val (workQueue1, unvisited2) = findNext(visited, unvisited, workQueue, idMap)
      val workQueue2 = sortSinks(workQueue1)
      try {
        val (x, q) = workQueue2.dequeue
        val (newSub, newMap) = applySubs(x, sub, m)
        newSub match {
          case Some(ns) =>
            if (isSink(visited.head)) Nil else loop(x :: visited, unvisited2, q, ns, newMap)
          case None =>
            val (errs, nu) = mkErrors(initial, x, s, handledEffs, contexts)
            s = nu
            errs
        }
      } catch {
        case _: NoSuchElementException => Nil
      }
    }

    (loop(List(initial), constrs0, Queue.empty, initialSub, idMap), s)
  }

  /** Extracts the two sides of an `Equality` constraint, returning `None` for other constraint kinds.  */
  private def extractTypes(constr: TypeConstraint): Option[(Type, Type)] = constr match {
    case TypeConstraint.Equality(consTpe1, consTpe2, _) => Some((consTpe1, consTpe2))
    case _ => None
  }

  /** Deduplicates source constraints whose right-hand side contains identical effect arguments.
    * Keeps the first occurrence and drops later duplicates.
    */
  private def filterOutDuplicateSources(sources: List[TypeConstraint]): List[TypeConstraint] = {
    sources.foldLeft(List.empty[TypeConstraint]) {
      case (acc, t@TypeConstraint.Equality(_, tpe2, _)) =>
        acc.find {
          case (TypeConstraint.Equality(_, x, _)) => consTypeArgs(x) == consTypeArgs(tpe2)
          case _ => false
        } match {
          case Some(_) => acc
          case None => t :: acc
        }
      case (acc, _) => acc
    }
  }

  /** Returns the effects present in `tpe1` but absent in `tpe2`, ignoring subtracted effects in both. */
  private def findDiffInTypes(tpe1: Type, tpe2: Type): List[Type] = {
    val x = consUsedTypeArgs(tpe1)
    val y = consUsedTypeArgs(tpe2)
    x.diff(y)
  }

  /** Walks constraints to find one whose provenance is `Source` or `ExpectType` and which
    * mentions `start`. Recurses through intermediate equality constraints to trace back the origin.
    */
  private def searchForSource(start: Type, constrs0: List[TypeConstraint]): Option[TypeConstraint] = {
    findType(start, constrs0).foldLeft(None: Option[TypeConstraint])((acc, t) =>
      if (acc.isDefined) acc else
        t match {
          case TypeConstraint.Equality(_, _, Provenance.Source(_, _, _)) => Some(t)
          case TypeConstraint.Equality(_, _, Provenance.ExpectType(_, _, _)) => Some(t)
          case TypeConstraint.Equality(tpe1, tpe2, _) =>
            val unvisited = constrs0.filter(_ != t)
            val a = (tpe: Type) => if (tpe != start) searchForSource(tpe, unvisited) else None
            a(tpe1).orElse(a(tpe2))
          case _ => None
        })
  }

  private def isPure(tpe: Type): Boolean = tpe match {
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => true
      case _ => false
    }
    case _ => false
  }

  /** Returns `true` iff `constr` is an `ExpectEffect` constraint */
  private def isSink(constr: TypeConstraint): Boolean = constr match {
    case TypeConstraint.Equality(_, _, prov) => prov match {
      case Provenance.ExpectEffect(_, _, _) => true
      case _ => false
    }
    case _ => false
  }

  /**
    * tries to make errors for mismatches in handled effects and the signature
    * @param sink type constraint of the signature/sink
    * @param contexts handler contexts
    */
  private def mkHandlerMismatch(sink: TypeConstraint, contexts: List[HandlerContext]): List[EffConflicted] = sink match {
    case TypeConstraint.Equality(tpe1, _, _) =>
      val handledEffectIsReturned = contexts.foldLeft(None: Option[(HandlerContext, SourceLocation)])((_, c) => {
        consUsedTypeArgs(tpe1).find(_ == c.handler) match {
          case Some(t) => Some((c, t.loc))
          case None => None
        }
      })
      handledEffectIsReturned match {
        case Some((c, sLoc)) => List(EffConflicted(TypeError.HandledEffectAppearsInSignature(typeToSym(c.handler).head, c.handler.loc, sLoc)))
        case None => Nil
      }
    case _ => Nil
  }

  /** Produces `UnhandledEffect` errors when `source` is the `run` constraint of a
    * known handler context and the effects inside the `run` block are not fully
    * covered by the handled effects.
    *
    * @param source   the constraint that originates the effect flow (expected to be a `run` constraint)
    * @param sink     the function-signature constraint that the effects flow into
    * @param contexts handler contexts describing what each `run` block handles
    * @return a list of `EffConflicted` errors for each unhandled effect
    */
  private def mkUnhandledError(source: TypeConstraint, sink: TypeConstraint, contexts: List[HandlerContext]): List[EffConflicted] = source match {
    case TypeConstraint.Equality(_, _, prov) => contexts.find(a => a.runConstraint == source).map {
      case HandlerContext(inRun, handled, _, _, handlerConstraint) => sink match {
        case TypeConstraint.Equality(tpe1, _, _) =>
          val unhandledEffs = consTypeArgs(inRun).diff(consTypeArgs(handled))
          unhandledEffs.map(uh => (EffConflicted(TypeError.UnhandledEffect(typeToSym(uh).head, typeToSym(tpe1).head, prov.loc, handlerConstraint.loc, tpe1.loc))))
        case _ => Nil
      }
      case _ => Nil
    }.getOrElse(Nil)

    case _ => Nil
  }

  /**
    * creates a list of effect errors
    *
    * @param source      source for the error
    * @param sink        sink for the error
    * @param sinks       set of all sinks that are currently unused
    * @param handledEffs set of handled effects
    * @return a list off errors and an updated set of unhandled effects
    */
  private def mkErrors(source: TypeConstraint, sink: TypeConstraint, sinks: Set[Type], handledEffs: Set[Type], contexts: List[HandlerContext])(implicit scope: RegionScope, renv: RigidityEnv): (List[EffConflicted], Set[Type]) = {
    var s: Set[Type] = sinks
    // extract source effect type from the source constraint
    val a = source match {
      case TypeConstraint.Equality(t1, t2, prov) => prov match {
        case Provenance.ExpectArgument(_, _, _, _, _) => Some((t2, prov))
        case Provenance.Source(_, _, _) => Some((t2, prov))
        case Provenance.ExpectType(_, _, _) => Some((t2, prov))
        case Provenance.Match(_, _, _) => Some((t2, prov))
        case Provenance.ExpectEffect(_, _, _) => Some((t1, prov))
        case _ => None
      }
      case _ => None
    }
    val b = a.map({ case (sourceTpe, sProv) =>
      val sourceSyms = typeToSym(sourceTpe)
      val sinkString = (sink: Type) => s"${EffSymOrRigidVar.format(consUsedTypeArgs(sink).flatMap(typeToSym))}"
      val filtered = (xs: Type, tpe1: Type) => {
        consUsedTypeArgs(xs).filterNot(x =>
          // an effect that is handled is not a source off an error
          contexts.exists(c => c.handled == x && consTypeArgs(c.inRun).contains(x))
           // neither is an effect that is in the sink
            || consTypeArgs(tpe1).contains(x)
            // flexible variables are never sources of an error
            || isFlexible(x)
        )
      }
      sink match {
        case TypeConstraint.Equality(tpe1, _, prov) =>
          // remove source effect from the set of unused effects
          s = s.diff(consUsedTypeArgs(sourceTpe).toSet)
          s = s.diff(handledEffs)
          if (tpe1 == sourceTpe)
            contexts.find(c => c.inRun == sourceTpe).map(c =>
              List(EffConflicted(TypeError.UnusedHandlerEffect(typeToSym(c.handler).head, c.handler.loc, tpe1.loc, source.loc)))
            ).getOrElse(Nil)
          else {
            val errs = prov match {
              case Provenance.ExpectEffect(expected, _, _) => expected match {
                case Type.Var(sym, _) =>
                  filtered(sourceTpe, tpe1).map(x => EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(RigidVar(sym)), typeToSym(x).head, sinkString(tpe1), expected.loc, source.loc)))
                case Type.Cst(tc, loc) => tc match {
                  case TypeConstructor.Pure =>
                    def mkPureEffErr(sourceEff: Type): EffConflicted = {
                      // we make a specific error if the source effect is IO
                      val isIO = typeToSym(sourceEff) match {
                        case Eff(symbol) :: Nil => symbol == Symbol.IO
                        case _ => false
                      }
                      val err: TypeError = (loc.isReal, isIO) match {
                        case (true, true) => TypeError.ExplicitlyPureFunctionUsesIO(loc, sProv.loc)
                        case (true, false) => TypeError.ExplicitlyPureFunctionUsesEffect(typeToSym(sourceEff).head, loc, sProv.loc)
                        case (false, true) => TypeError.ImplicitlyPureFunctionUsesIO(prov.loc, sProv.loc)
                        case (false, false) => TypeError.ImplicitlyPureFunctionUsesEffect(typeToSym(sourceEff).head, prov.loc, sProv.loc)
                      }
                      EffConflicted(err)
                    }

                    filtered(sourceTpe, tpe1).map(mkPureEffErr)
                  case TypeConstructor.Effect(sym, _) => sourceTpe match {
                    case Type.Cst(tc2, _) => tc2 match {
                      // source effects that are pure do not constitute an error
                      case TypeConstructor.Pure => Nil
                      case _ => List(EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(sym)), sourceSyms.head, sinkString(tpe1), loc, source.loc)))
                    }
                    case Type.Apply(_, _, _) =>
                      // filter out any source effect that is handled or is in the function signature, then create an error
                      filtered(sourceTpe, tpe1).map(x => EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(sym)), typeToSym(x).head, sinkString(tpe1), loc, source.loc)))
                    case _ => List(EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(sym)), sourceSyms.head, sinkString(tpe1), loc, source.loc)))
                  }
                  case _ => Nil
                }
                case Type.Apply(_, _, _) =>
                  val notInDef = findDiffInTypes(sourceTpe, expected)
                  notInDef.foldLeft(List.empty[Type])((acc, x) => if (acc.contains(x) || isFlexible(x) || isPure(x) || handledEffs.contains(x)) acc else x :: acc).map(x => EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(typeToSym(expected), typeToSym(x).head, sinkString(tpe1), expected.loc, source.loc)))
                case _ => Nil
              }
              case Provenance.ExpectArgument(expected, _, sym, _, _) => sym match {
                case ds: Symbol.DefnSym => List(EffConflicted(TypeError.ArgumentGivenWrongEffect(typeToSym(expected), sourceSyms, sink.loc, ds.loc, sProv.loc)))
                case _ => Nil
              }
              // wild edge case involving regions and pipes
              case Provenance.Match(_, _, _) => {
                filtered(sourceTpe, tpe1).map(x => EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(typeToSym(tpe1), typeToSym(x).head, sinkString(tpe1), prov.loc, x.loc)))
              }
              case _ => Nil
            }
            errs
          }
        case _ => Nil
      }

    }).getOrElse(Nil)
    val unhs = mkUnhandledError(source, sink, contexts)
    val hs = mkHandlerMismatch(sink,contexts)
    (hs ++ unhs ++ b, s)
  }

  /**
    * converts given type constraint to a Zhegalkin expression, then applies the given substitution, SVE is then applied to the result
    */
  private def applySubs(current: TypeConstraint, sub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]]], Map[Type, Int]) = {
    constraintToZhegalkin(current, idMap) match {
      case (Some((x, y)), nm) =>
        val sx = sub.apply(x)
        val sy = sub.apply(y)
        try {
          val newSub = SveAlgorithm.sveAll(List((sx, sy)))
          (Some(sub ++ newSub), nm)
        } catch {
          case _: BoolUnificationException => (None, nm)
        }
      case (_, nm) => (None, nm)
    }
  }

  /**
    * converts a single type constraint to a Zhegalkin expression and applies SVE on it
    * if the type constraint has both a sink and a source, then it will produce an error
    */
  private def initialSub(source: TypeConstraint, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Either[BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], List[EffConflicted]], Map[Type, Int]) = {
    constraintToZhegalkin(source, idMap) match {
      case (Some((x, y)), nm) =>
        try {
          (Left(SveAlgorithm.sveAll(List((x, y)))), nm)
        } catch {
          // sometimes a singular constraint has the sink on the left hand side and source on the right side
          case _: BoolUnificationException => source match {
            case TypeConstraint.Equality(tpe1, tpe2, prov) =>
              val newSource = TypeConstraint.Equality(tpe2, tpe2, prov)
              val newSink = TypeConstraint.Equality(tpe1, tpe1, prov)
              (Right(mkErrors(newSource, newSink, Set.empty[Type], Set.empty, Nil)._1), nm)
            case _ => (Right(Nil), nm)
          }
        }
      case (None, nm) => (Right(Nil), nm) // Could not generate errors
    }
  }

  /**
    * finds the next type constraints to be used in the algorithm and puts them into the workQueue
    *
    * i.e. finds all adjacent constraints
    *
    * @param visited   visited type constraints
    * @param unvisited unvisited type constraints: if an unvisited type constraint has a type in common with a visited one it will be added to the workQueue
    * @param workQueue work queue
    * @param idMap     id's of types in the Zhegalkin expressions
    */
  private def findNext(visited: List[TypeConstraint], unvisited: List[TypeConstraint], workQueue: Queue[TypeConstraint], idMap: Map[Type, Int]): (Queue[TypeConstraint], List[TypeConstraint]) = {
    visited.foldLeft((workQueue, unvisited)) {
      case ((wq, unvis), TypeConstraint.Equality(tpe1, tpe2, _)) =>
        // only include variables
        val f = (t: Type) => if (idMap.getOrElse(t, -1) < 0) findType(t, unvis) else Nil
        val b = (i: List[TypeConstraint], k: List[TypeConstraint]) => i ++ k
        val x = deconstructType(tpe1, f, b, Nil)
        val y = deconstructType(tpe2, f, b, Nil)
        ((x ++ y).foldLeft(wq)((acc, x) => acc.enqueue(x)), unvis.diff(x ++ y))

      case _ => (workQueue, unvisited)
    }
  }

  /**
    * finds all type constraints where tpe appears
    *
    * @param tpe     type to find
    * @param constr0 list of type constraints
    * @return constraints where tpe appears
    */
  private def findType(tpe: Type, constr0: List[TypeConstraint]): List[TypeConstraint] = {
    constr0.filter {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def isTpe(t: Type, t2: Type): Boolean = t match {
          case Type.Apply(_, _, _) => t.typeArguments.exists(isTpe(_, t2))
          case _ => t == t2
        }

        val a = (x: Boolean, y: Boolean) => x || y
        deconstructType(tpe, isTpe(tpe1, _), a, false) || deconstructType(tpe, isTpe(tpe2, _), a, false)
      case _ => false
    }
  }

  /**
    *
    * @param t       Type
    * @param f       the function to apply to the type
    * @param g       the function to apply to join two types in case of a Type.Apply
    * @param default default value to return when the function cannot be applied
    */
  private def deconstructType[A](t: Type, f: Type => A, g: (A, A) => A, default: A): A = t match {
    case Type.Var(_, _) => f(t)
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => f(t)
      case TypeConstructor.Effect(_, _) => f(t)
      case _ => default
    }
    case Type.Apply(tpe1, tpe2, _) => g(deconstructType(tpe1, f, g, default), deconstructType(tpe2, f, g, default))
    case _ => default
  }

  /**
    * creates a tuple Zhegalkin expressions from given constraint
    *
    * @param constr TypeConstraint
    * @param idMap  used for id's of variables and constants in the Zhegalkin expressions
    */
  private def constraintToZhegalkin(constr: TypeConstraint, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[(ZhegalkinExpr[CofiniteIntSet], ZhegalkinExpr[CofiniteIntSet])], Map[Type, Int]) = {
    extractTypes(constr) match {
      case Some((tpe1, tpe2)) =>
        typeToZhegalkin(tpe1, idMap) match {
          case (None, nm) => (None, nm)
          case (Some(xh1), nm) => typeToZhegalkin(tpe2, nm) match {
            case (Some(xh2), nnm) => (Some((xh1, xh2)), nnm)
            case (None, nnm) => (None, nnm)
          }
        }
      case None => (None, idMap)
    }
  }

  /**
    * checks for the debug effect in the list of constraints
    */
  private def isDebug(constrs: List[TypeConstraint]): Boolean = {
    constrs.exists {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def isDb(t: Type): Boolean = t match {
          case Type.Cst(tc, _) => tc match {
            case TypeConstructor.Effect(sym, _) => sym match {
              case Symbol.Debug => true
              case _ => false
            }
            case _ => false
          }
          case Type.Apply(tl, tr, _) => isDb(tl) || isDb(tr)
          case _ => false
        }

        isDb(tpe1) || isDb(tpe2)
      case _ => false
    }
  }

  /** Placeholder for a future greedy permutation strategy over the id map.
    * Currently returns `m` unchanged regardless of the substitution.
    */
  private def greedyPermutation(sub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], m: Map[Type, Int]): Map[Type, Int] = sub match {
    case BoolSubstitution(_) => m
    case _ => m
  }

  /**
    * convert a Type into a Zhegalkin expression and update the idMap if necessary
    *
    * @param tpe   Type to convert
    * @param idMap map containing ids of converted types
    * @return a tuple of Option[ZhegalkinExpr] and idMap, so an idMap is always returned
    */
  private def typeToZhegalkin(tpe: Type, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[ZhegalkinExpr[CofiniteIntSet]], Map[Type, Int]) = {
    val a = (default: Int, z: Int => ZhegalkinExpr[CofiniteIntSet]) => {
      val id = idMap.getOrElse(tpe, default)
      (Some(z(id)), idMap + (tpe -> id))
    }
    val varId = idMap.values.minOption.getOrElse(0).min(0) - 1
    val cstId = idMap.values.maxOption.getOrElse(0).max(0) + 1
    tpe match {
      case Type.Var(sym, _) =>
        if (renv.isFlexible(sym)) {
          a(varId, alg.mkVar)
        }
        else {
          a(cstId, alg.mkCst)
        }
      case Type.Cst(tc, _) => tc match {
        case TypeConstructor.Pure => a(cstId, alg.mkCst)
        case TypeConstructor.Effect(_, _) => a(cstId, alg.mkCst)
        case _ => (None, idMap)
      }
      case Type.Apply(_, _, _) => tpe.baseType match {
        case Type.Cst(tc, _) => tc match {
          case TypeConstructor.Difference =>
            tpe.typeArguments match {
              case left :: right :: _ =>
                typeToZhegalkin(left, idMap) match {
                  case (Some(x), nm) => typeToZhegalkin(right, nm) match {
                    case (Some(y), nnm) => (Some(alg.mkAnd(x, alg.mkNot(y))), nnm)
                    case c => c
                  }
                  case b => b
                }

              case _ => (None, idMap)
            }
          case TypeConstructor.Union =>
            tpe.typeArguments match {
              case left :: right :: _ =>
                typeToZhegalkin(left, idMap) match {
                  case (Some(x), nm) => typeToZhegalkin(right, nm) match {
                    case (Some(y), nnm) => (Some(alg.mkOr(x, y)), nnm)
                    case c => c
                  }
                  case b => b
                }

              case _ => (None, idMap)
            }

          case _ => (None, idMap)

        }
        case _ => (None, idMap)
      }
      case _ => (None, idMap)
    }
  }

  private def isFlexible(tpe: Type)(implicit scope: RegionScope, renv: RigidityEnv): Boolean = tpe match {
    case Type.Var(sym, _) => renv.isFlexible(sym)
    case _ => false
  }

  /** TODO remove this function and use HandlerContext instead
    * Collects all effect types that are subtracted (handled) on the right-hand
    * side of `constr`. Recursively inspects `Complement`, `Union`,
    * `Intersection`, `SymmetricDiff`, and `Difference` type constructors;
    * for `Difference` the right-hand argument is the handled set.
    */
  private def findHandled(constr: TypeConstraint): Set[Type] = constr match {
    case TypeConstraint.Equality(_, tpe, _) =>
      def a(t: Type): Set[Type] = t match {
        case Type.Apply(tpe1, tpe2, _) => t.typeConstructor match {
          case Some(value) => value match {
            case TypeConstructor.Complement => a(tpe1) ++ a(tpe2)
            case TypeConstructor.Union => a(tpe1) ++ a(tpe2)
            case TypeConstructor.Intersection => a(tpe1) ++ a(tpe2)
            case TypeConstructor.Difference => t.typeArguments match {
              case _ :: rhs :: Nil => consTypeArgs(rhs).toSet
              case _ => Set.empty
            }
            case TypeConstructor.SymmetricDiff => a(tpe1) ++ a(tpe2)
            case _ => Set.empty
          }
          case None => Set.empty
        }
        case _ => Set.empty
      }

      a(tpe)
    case _ => Set.empty
  }

  private def pureSource(typeConstraint: TypeConstraint) = typeConstraint match {
    case TypeConstraint.Equality(_, tpe2, _) => isPure(tpe2)
    case _ => false
  }

  /** Flattens `tpe` into a list of `EffSymOrRigidVar` tokens.
    * Effect constants become `Eff(sym)`, type variables become `RigidVar(sym)`,
    * `Union` applications are recursed into, and everything else yields `Nil`.
    */
  private def typeToSym(tpe: Type): List[EffSymOrRigidVar] = tpe match {
    case Type.Var(sym, _) => List(RigidVar(sym))
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => List(Eff(Symbol.mkEffSym("Pure")))
      case TypeConstructor.Effect(sym, _) => List(Eff(sym))
      case TypeConstructor.Union => Nil
      case _ => Nil
    }
    case Type.Apply(tl, tr, _) => typeToSym(tl) ++ typeToSym(tr)
    case _ => Nil
  }

  /** Splits a large `Equality` constraint into smaller ones to keep Zhegalkin
    * expressions manageable. When the right-hand side contains more than five
    * effect type arguments, the compound type is decomposed into a chain of
    * fresh intermediate equality constraints connected by `Match` provenance.
    * Constraints with five or fewer arguments, and all non-`Equality` constraints,
    * are returned unchanged (or as `Nil` for non-equality kinds).
    */
  private def simplifyConstraint(constr: TypeConstraint)(implicit scope: RegionScope, flix: Flix): List[TypeConstraint] = constr match {
    case TypeConstraint.Equality(tpe1, tpe2, prov) =>
      val tc = (t: Type) => t.typeConstructor match {
        case None => None
        case Some(a) => a match {
          case TypeConstructor.Complement => Some(Type.Complement)
          case TypeConstructor.Union => Some(Type.Union)
          case TypeConstructor.Intersection => Some(Type.Intersection)
          case TypeConstructor.Difference => Some(Type.Difference)
          case TypeConstructor.SymmetricDiff => Some(Type.SymmetricDiff)
          case _ => None
        }
      }

      def a(tcOpt: Option[Type], tpes: List[Type]): List[(Type, Option[TypeConstraint])] = {
        val lhs = Type.Var(Symbol.freshKindedTypeVarSym(VarText.Absent, Kind.Eff, false, prov.loc), prov.loc)
        tpes match {
          case x :: Nil => (x, None) :: Nil
          case left :: right :: _ =>
            val lRest = a(tc(left), left.typeArguments)
            val rRest = a(tc(right), right.typeArguments)
            val (rVar, _) = rRest.headOption.getOrElse((right, constr))
            val (lVar, _) = lRest.headOption.getOrElse((left, constr))
            tcOpt.map(base => Type.mkApply(base, List(lVar, rVar), prov.loc)) match {
              case Some(apply) => (lhs, Some(TypeConstraint.Equality(lhs, apply, Provenance.Match(lhs, apply, prov.loc)))) :: lRest ::: rRest
              case None => Nil
            }
          case _ => Nil
        }
      }

      tpe2 match {
        case Type.Apply(_, _, _) =>
          if (consTypeArgs(tpe2).length > 5) {
            val res = a(tc(tpe2), tpe2.typeArguments)
            TypeConstraint.Equality(tpe1, res.head._1, prov) :: res.flatMap(_._2)
          }
          else constr :: Nil


        case _ => List(constr)
      }


    case _ => Nil
  }

  /** Builds a `HandlerContext` from a `Handler` provenance constraint.
    *
    * The right-hand side of a handler constraint encodes the type as
    * `(inRun - handled) ∪ handlerEffect`. This function extracts those
    * components and searches `constrs0` for the source constraint that
    * introduced `inRun`, returning a fully populated `HandlerContext` when
    * found or `None` otherwise.
    *
    * @param constr   the equality constraint to inspect
    * @param constrs0 the full constraint list used for source lookup
    * @return a `HandlerContext` if one could be made, otherwise `None`
    */
  private def visitHandlers(constr: TypeConstraint, constrs0: List[TypeConstraint]): Option[HandlerContext] = constr match {
    case TypeConstraint.Equality(_, handled, Provenance.Handler(_, _, _)) =>
      // we get the type of (evar - handled effect) + effect of handler
      // we need the evar to be able to see which effects are handled
      consTypeArgs(handled) match {
        case inRun :: h :: hr :: Nil =>
          searchForSource(inRun, constrs0.filter(_ != constr)).flatMap {
            case source@TypeConstraint.Equality(_, tpe2, _) => Some(HandlerContext(tpe2, h, hr, source, constr))
            case _ => None
          }

        case inRun :: hr :: Nil =>
          searchForSource(inRun, constrs0.filter(_ != constr)).flatMap {
            case source@TypeConstraint.Equality(_, tpe2, _) =>
              Some(HandlerContext(tpe2, tpe2, hr, source, constr))
            case _ => None
          }
        case _ => None
      }

    case _ => None
  }

  /** Groups together all information needed to reason about a single effect handler.
    *
    * @param inRun             the effect type of the body of the `run` block
    * @param handled           the effect type that the handler absorbs
    * @param handler           the effect type of the handler itself
    * @param runConstraint     the constraint that introduced `inRun` as the `run`-body effect
    * @param handlerConstraint the `Handler`-provenance constraint that describes this handler
    */
  private case class HandlerContext(inRun: Type, handled: Type, handler: Type, runConstraint: TypeConstraint, handlerConstraint: TypeConstraint)
}

