/*
 * Copyright 2026 Alexander Sommer, Samuel Skovbakke
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.phase.typer

import ca.uwaterloo.flix.language.ast.shared.EffSymOrRigidVar.{Eff, RigidVar}
import ca.uwaterloo.flix.language.ast.shared.{EffSymOrRigidVar, RegionScope}
import ca.uwaterloo.flix.language.errors.TypeError
import ca.uwaterloo.flix.language.ast.{Rigidity, RigidityEnv, SourceLocation, Symbol, Type, TypeConstructor}
import ca.uwaterloo.flix.language.phase.typer.EffectProvenance.Vertex.{ArgVertex, CstVertex, IOVertex, PureExplicitVertex, PureImplicitVertex, RigidVarVertex, SignatureVertex, VarVertex, sameType, symbol}
import ca.uwaterloo.flix.language.phase.typer.EffectProvenance.NodeType.{ArgNode, IntermediateNode, SinkNode, SourceNode}
import ca.uwaterloo.flix.language.phase.typer.TypeConstraint.EffConflicted

/**
  * Analyzes constraints generated by ConstraintSolver in order to provide code actions,
  * inlay hints and better error messages.
  *
  * This module constructs a directed graph representing effect flow from type constraints
  * and performs breadth-first search to identify specific paths from effect to another effect.
  * This helps generate specific errors that help with diagnosing effect related errors.
  * It generates lists of all paths from some effect flowing into another (conflicting) effect.
  */
object EffectProvenance {
  /**
    * Represents a directed edge in the effect constraint graph.
    */
  private case class Edge(v1: Vertex, v2: Vertex, loc: SourceLocation)

  /**
    * Represents a directed graph of effect flow.
    */
  private case class Graph(vertices: List[Vertex], edges: List[Edge])

  /**
    * Represents the lattices used for analysis of effects
    */
  trait Lattice[A] {
    def bottom: A
    def lub(x: A, y: A): A
    def leq(x: A, y: A): Boolean
  }

  private class PowerSetLattice[K] extends Lattice[Set[K]] {
    def bottom: Set[K] = Set.empty

    def lub(x: Set[K], y: Set[K]): Set[K] = x union y

    def leq(x: Set[K], y: Set[K]): Boolean = x.subsetOf(y)
  }

  private class MapLattice[K, V](val subLattice: Lattice[V]) extends Lattice[Map[K, V]] {
    def bottom: Map[K, V] = Map.empty

    def lub(x: Map[K, V], y: Map[K, V]): Map[K, V] = {
      x.foldLeft(y) {
        case (acc, (v, set)) =>
          val ys = acc.getOrElse(v, subLattice.bottom)
          acc + (v -> subLattice.lub(ys, set))
      }
    }

    def leq(x: Map[K, V], y: Map[K, V]): Boolean = {
      x.forall {
        case (v, set) => subLattice.leq(set, y.getOrElse(v, subLattice.bottom))
      }
    }
  }

  /**
    * Looks up the effect set associated with a vertex in the map lattice.
    *
    * @param vertex  the vertex to look up
    * @param lattice the current map-lattice state
    * @return the set of (vertex, location) pairs associated with the given vertex,
    *         or the empty set if no entry matches
    */
  private def lookupVertex(vertex: Vertex, lattice: Map[Vertex, Set[(Vertex, SourceLocation)]]): Set[(Vertex, SourceLocation)] = {
    lattice.foldLeft(Set.empty[(Vertex, SourceLocation)]) {
      case (acc, (arg@ArgVertex(_, _), s)) => if (arg.lookup(vertex).isDefined) s else acc
      case (acc, (v, xs))                  => if (v == vertex) xs else acc
    }
  }

  /**
    * Represents a vertex in the effect constraint graph.
    *
    * A Vertex represents one of:
    *   - Explicitly Pure function
    *   - Implicitly Pure function
    *   - The IO effect
    *   - Effect constants, i.e. user-defined effects
    *   - Effect variables
    */
  sealed trait Vertex

  object Vertex {
    /**
      * Represents the effects defined in a function signature's argument
      */
    case class ArgVertex(argEff: List[Vertex], loc: SourceLocation) extends Vertex {
      /**
        * Lookup method which deconstructs an argvertex with a special case for argvertex
        * if @vertex is an ArgVertex then, lookup attempts to find a vertex in argEff which is contained in @vertex
        * this edge case appears when a function call is given as an argument to another function
        */
      def lookup(vertex: Vertex): Option[Vertex] = vertex match {
        case ArgVertex(otherEffs, _) => argEff.find(otherEffs.contains)
        case v => argEff.find(_ == v)
      }
    }

    /**
      * Explicitly Pure function (has a real source location).
      *
      * Example: def foo(): Unit \ {} = ()
      *
      * @param loc the source location of {}
      */
    case class PureExplicitVertex(loc: SourceLocation) extends Vertex

    /**
      * Implicitly Pure function.
      *
      * Example: def foo(): Unit = ()
      *
      * @param loc the synthetic location, which is the position immediately to the right of the return type.
      */
    case class PureImplicitVertex(loc: SourceLocation) extends Vertex

    /**
      * User-defined effect.
      *
      * @param sym the effect symbol
      * @param loc the source location where the effect is called
      */
    case class CstVertex(sym: Symbol.EffSym, loc: SourceLocation) extends Vertex

    /**
      * The IO effect.
      *
      * @param loc the source location where IO is called
      */
    case class IOVertex(loc: SourceLocation) extends Vertex

    /**
      * A rigid effect variable
      *
      * @param sym the effect variable symbol
      * @param loc the location of the rigid effect variable
      */
    case class RigidVarVertex(sym: Symbol.KindedTypeVarSym, loc: SourceLocation) extends Vertex

    /**
      * Represents the effects in the signature of a function
      */
    case class SignatureVertex(effs: List[Vertex], loc: SourceLocation) extends Vertex {
      def symbols: List[EffSymOrRigidVar] = {
        effs.flatMap(symbol)
      }
    }

    /**
      * Effect variable.
      *
      * @param sym the effect variable symbol
      */
    case class VarVertex(sym: Symbol.KindedTypeVarSym) extends Vertex

    def symbol(v: Vertex): Option[EffSymOrRigidVar] = v match {
      case PureExplicitVertex(_) | PureImplicitVertex(_) => Some(Eff(Symbol.mkEffSym("Pure")))
      case CstVertex(sym, _) => Some(Eff(sym))
      case IOVertex(_) => Some(Eff(Symbol.IO))
      case RigidVarVertex(sym, _) => Some(RigidVar(sym))
      case _ => None
    }

    /**
      * Determines if two vertices are of the same type
      *
      * e.g. IO(1:1) = IO(2:2) indeterminate of location
      */
    def sameType(v1: Vertex, v2: Vertex): Boolean = (v1, v2) match {
      case (IOVertex(_), IOVertex(_)) => true
      case (PureExplicitVertex(_), PureImplicitVertex(_)) => true
      case (PureExplicitVertex(_), PureExplicitVertex(_)) => true
      case (PureImplicitVertex(_), PureImplicitVertex(_)) => true
      case (PureImplicitVertex(_), PureExplicitVertex(_)) => true
      case (CstVertex(sym1, _), CstVertex(sym2, _)) => sym1 == sym2
      case (RigidVarVertex(sym1, _), RigidVarVertex(sym2, _)) => sym1 == sym2
      case _ => false
    }
  }

  /**
    * Represents the type of node constructed in the effect provenance graph
    *
    * This trait allows to differentiate between two Vertices of the same type, differently, determined by the NodeType
    *
    * For example an IO Vertex in a signature, e.g. f(): Unit \ IO
    * is constructed differently than one that appears in a source node. e.g. println("42")
    *
    * This trait is only used when constructing the graph
    */
  sealed trait NodeType

  object NodeType {
    case object ArgNode extends NodeType

    case object SinkNode extends NodeType

    case object IntermediateNode extends NodeType

    case object SourceNode extends NodeType
  }

  /**
    * Builds an effect conflict graph from given constraints.
    * Then analyzes the effect conflict graph and returns a list of effect conflicts.
    *
    * Returns a list of effect conflicts if any are found, or None if no good effect error could be made.
    * A conflict is: a path from an effect to a differing effect. E.g. IO -> ... -> {}.
    * This is the main entry point for effect provenance analysis.
    *
    * @param constrs0 the list of type constraints to analyze
    * @return a list of conflicts if conflicts could be found, None otherwise
    */
  def getErrors(constrs0: List[TypeConstraint])(implicit scope: RegionScope, renv: RigidityEnv): Option[List[EffConflicted]] = {
    val graph = buildGraph(constrs0)
    graph.flatMap(analysis)
  }

  /**
    * Performs reaching definitions analysis for each vertex in the graph
    *
    * @param graph the graph constructed in buildGraph
    * @return option list of errors
    */
  private def analysis(graph: Graph): Option[List[EffConflicted]] = {

    val subLattice = new PowerSetLattice[(Vertex, SourceLocation)]()

    val lattice = new MapLattice[Vertex, Set[(Vertex, SourceLocation)]](subLattice)

    def transfer(ml: Map[Vertex, Set[(Vertex, SourceLocation)]]): Map[Vertex, Set[(Vertex, SourceLocation)]] = {
      graph.edges.foldLeft(ml) {
        case (acc, Edge(from, to, loc)) =>
          val v1 = lookupVertex(from, acc)
          val v2 = lookupVertex(to, acc)
          val pointsTo = subLattice.lub(subLattice.lub(v1, v2), Set((from, loc)))
          val e: Map[Vertex, Set[(Vertex, SourceLocation)]] = Map(to -> pointsTo)
          lattice.lub(acc, e)
      }
    }

    var elmCurr = lattice.bottom
    var cont = true
    while (cont) {
      val elmNext = transfer(elmCurr)
      if (elmNext != elmCurr) elmCurr = elmNext
      else cont = false
    }

    val res = elmCurr.foldLeft(List.empty[EffConflicted]) {
      case (acc, (v, vs)) =>
        val filtered: Set[(Vertex, SourceLocation)] = vs.filterNot {
          case (VarVertex(_), _) => true
          case _ => false
        }
        if (isConflicting(v, filtered)) mkErrors(v, vs) ::: acc else acc
    }
    if (res.isEmpty) None else Some(res)
  }

  /**
    * Constructs an effect provenance graph from type constraints.
    *
    * The graph represents flow of effects through the program. An edge from A to B
    * means that effect A flows to B.
    *
    * @param constraints the type constraints to analyze
    * @return Some(graph) if one or more edges could be created, otherwise None
    */
  private def buildGraph(constraints: List[TypeConstraint])(implicit scope: RegionScope, renv: RigidityEnv): Option[Graph] = {
    var flow: List[Edge] = List()
    var v: Set[Vertex] = Set.empty
    constraints.foreach {
      case TypeConstraint.Equality(tpe1, tpe2, prov) =>
        val inf = prov match {
          case TypeConstraint.Provenance.ExpectEffect(effs, _, _) =>
            val l = if (effs.loc.isReal) effs.loc else prov.loc
            Some((SinkNode, IntermediateNode, l))
          case TypeConstraint.Provenance.Source(_, _, _) => Some((IntermediateNode, SourceNode, prov.loc))
          case TypeConstraint.Provenance.Match(_, _, _) => Some((IntermediateNode, IntermediateNode, prov.loc))
          case TypeConstraint.Provenance.ExpectType(_, _, _) => Some((IntermediateNode, SourceNode, prov.loc))
          case TypeConstraint.Provenance.ExpectArgument(arg, _, _, _, _) => Some((ArgNode, IntermediateNode, arg.loc))
          case _ => None
        }
        inf.map {
          case (nt1, nt2, loc) =>
            val v1 = toVertex(tpe1, loc, nt1)
            val v2 = toVertex(tpe2, loc, nt2)
            (v1, v2) match {
              case (Nil, _) => ()
              case (_, Nil) => ()
              case (toVertices, fromVertices) =>
                v ++= fromVertices.toSet
                v ++= toVertices.toSet
                flow :::= createEdges(fromVertices, toVertices, prov.loc)
            }
        }

      case _ => ()
    }
    if (flow.isEmpty) return None
    Some(Graph(v.toList, flow))
  }

  /**
    * Creates directed edges from each vertex in `fromVertices` to each vertex in `toVertices`.
    *
    * For every (from, to) pair, one edge is created with the given source location.
    *
    * @param fromVertices the source vertices
    * @param toVertices   the target vertices
    * @param loc          the source location to attach to each created edge
    * @return a list of edges connecting every from-vertex to every to-vertex
    */
  private def createEdges(fromVertices: List[Vertex], toVertices: List[Vertex], loc: SourceLocation): List[Edge] = {
    fromVertices.foldLeft(List.empty[Edge]) {
      (acc, from) =>
        toVertices.foldLeft(acc) {
          (acc2, to) => Edge(from, to, loc) :: acc2
        }
    }
  }

  /**
    * Checks whether a sink vertex conflicts with the set of vertices flowing into it.
    *
    * The rules are:
    *   - Effect variables (`VarVertex`) never conflict, as they can unify with anything.
    *   - A `SignatureVertex` conflicts if any declared effect is unused, or if any
    *     incoming effect is not declared in the signature.
    *   - A pure vertex (`PureImplicitVertex` or `PureExplicitVertex`) conflicts if any
    *     effect flows into it (i.e., the incoming set is non-empty).
    *   - Any other concrete vertex conflicts if it does not match all incoming vertices
    *     exactly (by type).
    *
    * @param v1 the sink vertex
    * @param v2 the set of (vertex, location) pairs flowing into the sink
    * @return true if there is a conflict, false otherwise
    */
  private def isConflicting(v1: Vertex, v2: Set[(Vertex, SourceLocation)]): Boolean = {
    v1 match {
      case VarVertex(_) => false
      case SignatureVertex(effs, _) =>
        // All the effects in the signature must be used:
        val used = effs.forall(e => v2.exists { case (i, _) => sameType(e, i) })
        // All the used effects must be in the signature:
        val defined = v2.forall { case (e, _) => effs.exists(i => sameType(e, i)) }
        !used || !defined
      case PureImplicitVertex(_) | PureExplicitVertex(_) => v2.nonEmpty
      case x => !v2.exists { case (y, _) => sameType(x, y) } || !v2.forall { case (y, _) => sameType(x, y) }
    }

  }

  /**
    * Produces conflict errors for an argument vertex whose expected effect set does not
    * match the effects that flow into it.
    *
    * Returns an empty list when:
    *   - The argument effect list is empty.
    *   - The argument expects exactly one rigid-variable or flexible-variable effect.
    *
    * Otherwise, for each incoming effect that is not among the expected argument effects,
    * or for each expected argument effect that is absent from the incoming effects,
    * an `ArgumentGivenWrongEffect` error is emitted.
    *
    * @param xs   the effects expected by the argument (from the `ArgVertex`)
    * @param ys   the effects that actually flow into the argument, with their source locations
    * @param aLoc the source location of the argument position itself
    * @return a list of `EffConflicted` errors (may be empty)
    */
  private def mkArgErrors(xs: List[Vertex], ys: List[(Vertex, SourceLocation)], aLoc: SourceLocation) = xs match {
    case Nil => Nil
    // If a function that expects an argument with a single rigid variable,
    // then it is not possible to have an error
    case RigidVarVertex(_, _) :: Nil => Nil
    case VarVertex(_) :: Nil => Nil
    case _ =>
      val prov = ys.sortBy(_._2).lastOption.map(_._2)

      val errOpt = (v: (Vertex, SourceLocation)) => v match {
        case (PureImplicitVertex(_), provLoc) => Some(TypeConstraint.EffConflicted(TypeError.ArgumentGivenWrongEffect(xs.flatMap(Vertex.symbol), List(Eff(Symbol.mkEffSym("Pure"))), prov.getOrElse(provLoc), aLoc, provLoc)))
        case (IOVertex(loc), provLoc) => Some(TypeConstraint.EffConflicted(TypeError.ArgumentGivenWrongEffect(xs.flatMap(Vertex.symbol), List(Eff(Symbol.IO)), prov.getOrElse(provLoc), aLoc, loc)))
        case (CstVertex(sym, loc), provLoc) => Some(TypeConstraint.EffConflicted(TypeError.ArgumentGivenWrongEffect(xs.flatMap(Vertex.symbol), List(Eff(sym)), prov.getOrElse(provLoc), aLoc, loc)))
        case (RigidVarVertex(sym, loc), provLoc) => Some(TypeConstraint.EffConflicted(TypeError.ArgumentGivenWrongEffect(xs.flatMap(Vertex.symbol), List(RigidVar(sym)), loc, aLoc, provLoc)))
        case _ => None
      }

      // checks if arguments are used on the right hand side
      val a = !xs.forall(e => ys.exists(i => sameType(e, i._1)))
      // checks if the right hand side are used in the arguments
      val b = !ys.forall {
        // Ignore flexible variables
        case (VarVertex(_), _) => true
        case i => xs.exists(e => sameType(e, i._1))
      }
      if (a || b) ys.flatMap(errOpt) else Nil
  }

  /**
    * Produces an error when an implicitly-pure function body performs an effectful operation.
    *
    * Handles two cases:
    *   - The body performs IO (`ImplicitlyPureFunctionUsesIO`).
    *   - The body uses a user-defined or rigid-variable effect (`ImplicitlyPureFunctionUsesEffect`).
    *
    * @param source the vertex representing the effect that was observed
    * @param sink   the `PureImplicitVertex` representing the implicitly-pure declaration
    * @return `Some(error)` if the combination is a known implicit-pure conflict, `None` otherwise
    */
  private def mkImplicitPureError(source: Vertex, sink: Vertex, provLoc: SourceLocation): Option[EffConflicted] = (source, sink) match {
    case (IOVertex(_), PureImplicitVertex(loc2)) => Some(TypeConstraint.EffConflicted(TypeError.ImplicitlyPureFunctionUsesIO(loc2, provLoc)))
    case (CstVertex(sym, _), PureImplicitVertex(loc2)) => Some(TypeConstraint.EffConflicted(TypeError.ImplicitlyPureFunctionUsesEffect(Eff(sym), loc2, provLoc)))
    case (RigidVarVertex(sym1, loc1), PureImplicitVertex(loc2)) => Some(TypeConstraint.EffConflicted(TypeError.ImplicitlyPureFunctionUsesEffect(RigidVar(sym1), loc2, loc1)))
    case _ => None
  }

  /**
    * Produces an error when an explicitly-pure function body performs an effectful operation.
    *
    * Handles two cases:
    *   - The body performs IO (`ExplicitlyPureFunctionUsesIO`).
    *   - The body uses a user-defined or rigid-variable effect (`ExplicitlyPureFunctionUsesEffect`).
    *
    * @param source the vertex representing the effect that was observed
    * @param sink   the `PureExplicitVertex` representing the `{}` annotation
    * @return `Some(error)` if the combination is a known explicit-pure conflict, `None` otherwise
    */
  private def mkExplicitPureError(source: Vertex, sink: Vertex, provLoc: SourceLocation): Option[EffConflicted] = (source, sink) match {
    case (IOVertex(_), PureExplicitVertex(loc2)) => Some(TypeConstraint.EffConflicted(TypeError.ExplicitlyPureFunctionUsesIO(loc2, provLoc)))
    case (CstVertex(sym, _), PureExplicitVertex(loc2)) => Some(TypeConstraint.EffConflicted(TypeError.ExplicitlyPureFunctionUsesEffect(Eff(sym), loc2, provLoc)))
    case (RigidVarVertex(sym1, loc1), PureExplicitVertex(loc2)) => Some(TypeConstraint.EffConflicted(TypeError.ExplicitlyPureFunctionUsesEffect(RigidVar(sym1), loc2, loc1)))
    case _ => None
  }

  /**
    * Produces an `EffectfulFunctionUsesOtherEffect` error for a signature with multiple effects
    *
    * Used for signature mismatch reporting where multiple conflicting effects flow into
    * a single declared effect.
    *
    * @param source   the declared-effect source vertex (IO, user-defined effect, or rigid variable)
    * @param symList  the list of incoming effect symbols that conflict with the sink
    * @param lhsLoc   the source location of the left-hand side (the declared effect)
    * @param provLoc  the source location of the provenance (where the conflict originates)
    * @return `Some(error)` if the sink is a recognized concrete effect, `None` otherwise
    */
  private def mkEffectfulErrorBySource(source: Vertex, symList: List[EffSymOrRigidVar], lhsLoc: SourceLocation, provLoc: SourceLocation): Option[EffConflicted] = source match {
    case IOVertex(_) => Some(TypeConstraint.EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(symList, Eff(Symbol.IO), lhsLoc, provLoc)))
    case CstVertex(sym, _) => Some(TypeConstraint.EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(symList, Eff(sym), lhsLoc, provLoc)))
    case RigidVarVertex(sym, _) => Some(TypeConstraint.EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(symList, RigidVar(sym), lhsLoc, provLoc)))
    case _ => None

  }

  /**
    * Produces an `EffectfulFunctionUsesOtherEffect` error for a signature with a single effect.
    *
    * This overload handles pairwise effect conflicts, where a single source effect flows
    * into a sink that declares a different concrete effect. All combinations of
    * IO, user-defined effects, and rigid variables are covered.
    *
    * @param source   the vertex representing the effect that flows in
    * @param sink     the vertex representing the declared (conflicting) effect
    * @param provLoc  the source location of the provenance (where the conflict originates)
    * @return `Some(error)` if both vertices are recognized concrete effects, `None` otherwise
    */
  private def mkEffectfulErrorBySink(sink: Vertex, source: Vertex, provLoc: SourceLocation): Option[EffConflicted] = {
    ((source, symbol(source)) match {
      case (PureExplicitVertex(_) | PureImplicitVertex(_), _) => None
      case (_, Some(sym)) => Some(sym)
      case (_, None) => None
    }).flatMap(sourceSym => sink match {
      case CstVertex(sym2, loc2) => Some(TypeConstraint.EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(sym2)), sourceSym, loc2, provLoc)))
      case IOVertex(loc2) => Some(TypeConstraint.EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(Symbol.IO)), sourceSym, loc2, provLoc)))
      case RigidVarVertex(sym, loc2) =>  Some(TypeConstraint.EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(RigidVar(sym)), sourceSym, loc2, provLoc)))
      case _ => None

    })
  }

  /**
    * Produces an `UnusedEffectInSignature` error for a sink vertex whose declared effect
    * is never actually used in the function body.
    *
    * @param sink the vertex representing the unused declared effect
    * @return `Some(error)` if the sink is a recognized concrete effect, `None` otherwise
    */
  private def mkUnusedError(sink: Vertex): Option[EffConflicted] = sink match {
    case IOVertex(loc) => Some(TypeConstraint.EffConflicted(TypeError.UnusedEffectInSignature(Eff(Symbol.IO), loc)))
    case CstVertex(sym, loc) => Some(TypeConstraint.EffConflicted(TypeError.UnusedEffectInSignature(Eff(sym), loc)))
    case RigidVarVertex(sym, loc) => Some(TypeConstraint.EffConflicted(TypeError.UnusedEffectInSignature(RigidVar(sym), loc)))
    case _ => None

  }

  /**
    * Identifies declared effects in `lhs` that are absent from the incoming effects in `rhs`.
    *
    * A "forward pass" checks the left-hand side (declared effects) against the right-hand side
    * (observed effects) and returns those declared effects that were never observed.
    * These represent effects declared in a signature that are never actually used.
    *
    * @param lhs the declared effect vertices (from the signature)
    * @param rhs the observed effect vertices with their source locations
    * @return the sub-list of `lhs` vertices that have no matching vertex in `rhs`
    */
  private def findUnused(lhs: List[Vertex], rhs: List[(Vertex, SourceLocation)]): List[Vertex] = {
    lhs.foldLeft(List.empty[Vertex]) {
      case (acc, e) => if (!rhs.exists(i => sameType(e, i._1))) e :: acc else acc
    }
  }

  /**
    * Identifies observed effects in `rhs` that are not declared in `lhs`.
    *
    * A "backwards pass" checks the right-hand side (observed effects) against the
    * left-hand side (declared effects) and returns those observed effects that have no
    * corresponding declaration. These represent effects used in a function body that
    * are missing from the signature.
    *
    * @param lhs the declared effect vertices (from the signature)
    * @param rhs the observed effect vertices with their source locations
    * @return the sub-list of `rhs` entries whose vertex has no matching vertex in `lhs`
    */
  private def findUndeclared(lhs: List[Vertex], rhs: List[(Vertex, SourceLocation)]): List[(Vertex, SourceLocation)] = {
    rhs.foldLeft(List.empty[(Vertex, SourceLocation)]) {
      case (acc, e) => if (!lhs.exists(i => sameType(e._1, i))) e :: acc else acc
    }
  }

  /**
    * Produces errors for a `SignatureVertex` whose declared effects do not match the effects
    * that flow into it.
    *
    * Combines two checks:
    *   1. Forward pass: declared effects that are never used → `UnusedEffectInSignature` errors.
    *   2. Backward pass: observed effects not present in the declaration →
    *      `EffectfulFunctionUsesOtherEffect` errors.
    *
    * @param lhs     the declared effect vertices from the signature
    * @param rhs     the observed effect vertices with their source locations
    * @param symList the symbolic names of all declared effects (used in error messages)
    * @param lhsLoc  the source location of the signature declaration
    * @return a list of `EffConflicted` errors (may be empty)
    */
  private def mkSignatureErrors(lhs: List[Vertex], rhs: List[(Vertex, SourceLocation)], symList: List[EffSymOrRigidVar], lhsLoc: SourceLocation) = {
    val unused = findUnused(lhs, rhs)
    val e1: List[EffConflicted] = if (unused.nonEmpty) unused.flatMap(mkUnusedError) else Nil

    // all of the used effects must be in the signature:
    val undefined = findUndeclared(lhs, rhs)
    val e2: List[EffConflicted] =
      if (undefined.nonEmpty)
        undefined.flatMap{case (e, provLoc) => mkEffectfulErrorBySource(e, symList, lhsLoc, provLoc)}
      else Nil
    e1 ++ e2
  }

  /**
    * Dispatches error construction for a given sink vertex and its set of incoming vertices.
    *
    * Routes to the appropriate error-making helper depending on the kind of sink:
    *   - `ArgVertex`: delegates to `mkArgErrors`.
    *   - `SignatureVertex` with a single effect: reports unused errors and recurses on the single element.
    *   - `SignatureVertex` with multiple effects: delegates to `mkSignatureErrors`.
    *   - Any other concrete vertex: for each incoming vertex that differs in type, attempts
    *     `mkEffectfulError`, `mkExplicitPureError`, and `mkImplicitPureError`.
    *
    * @param sink     the sink vertex from the map lattice
    * @param incoming the set of (vertex, location) pairs that reach the sink
    * @return a list of `EffConflicted` errors (may be empty)
    */
  private def mkErrors(sink: Vertex, incoming: Set[(Vertex, SourceLocation)]): List[EffConflicted] = {
    (sink, incoming.toList) match {
      case (ArgVertex(xs, aLoc), ys) => mkArgErrors(xs, ys, aLoc)
      case (s@SignatureVertex(xs, sigLoc), ys) => xs match {
        case Nil => Nil
        case x :: Nil =>
          val xUnused = findUnused(List(x), ys).nonEmpty
          if (xUnused) mkUnusedError(x).toList ::: mkErrors(x, ys.toSet)
          else mkErrors(x, ys.toSet)
        case _ => mkSignatureErrors(xs, ys, s.symbols, sigLoc)
      }
      case (x, ys) => ys.filter(e => !sameType(x, e._1)).flatMap { case (y, provLoc) =>
        val a = mkEffectfulErrorBySink(x, y, provLoc) :: mkExplicitPureError(y, x, provLoc) :: mkImplicitPureError(y, x, provLoc) :: Nil
        a.flatten
      }
    }
  }

  /**
    * Converts a type into its vertex representation(s) given a node type context.
    *
    * The conversion handles the following cases:
    *   - `Type.Var`: rigid variables become `RigidVarVertex`, flexible ones become `VarVertex`.
    *   - `Type.Cst` with `Pure`: `PureExplicitVertex` (if the location is real) or
    *     `PureImplicitVertex` (synthetic location).
    *   - `Type.Cst` with `Effect(IO)`: `IOVertex`, with location chosen based on node type.
    *   - `Type.Cst` with a user-defined effect: `CstVertex`.
    *   - `Type.Apply` (union types): recursively decomposes both branches and concatenates
    *     their vertices. Only `TypeConstructor.Union` nodes are expanded; all other
    *     constructors yield an empty list.
    *
    * The outer `vtpe` also governs how the resulting list is wrapped:
    *   - `ArgNode`  → wrapped in a single `ArgVertex`.
    *   - `SinkNode` → wrapped in a single `SignatureVertex`.
    *   - `IntermediateNode` / `SourceNode` → returned as-is.
    *
    * Returns an empty list for types that have no effect representation (e.g., value types).
    *
    * @param tpe      the type to convert
    * @param constLoc the source location of the enclosing constraint (used as a fallback)
    * @param vtpe     the role this type plays in the constraint graph
    * @return the list of vertices representing this type's effects
    */
  private def toVertex(tpe: Type, constLoc: SourceLocation, vtpe: NodeType)(implicit scope: RegionScope, renv: RigidityEnv): List[Vertex] = {

    def toVerticesFromType(tpe: Type, constLoc: SourceLocation, vtpe: NodeType)(implicit scope: RegionScope, renv: RigidityEnv): List[Vertex] = tpe match {
      case Type.Var(sym, loc) => renv.get(sym) match {
        case Rigidity.Flexible => List(VarVertex(sym))
        case Rigidity.Rigid => List(RigidVarVertex(sym, loc))
      }
      case Type.Cst(tc, loc) => tc match {
        case TypeConstructor.Pure => if (loc.isReal) List(PureExplicitVertex(loc)) else List(PureImplicitVertex(constLoc))
        case TypeConstructor.Effect(sym, _) => sym match {
          case Symbol.IO => vtpe match {
            case SinkNode | ArgNode | IntermediateNode => List(IOVertex(loc))
            case SourceNode => List(IOVertex(constLoc))
          }
          case Symbol.Debug => Nil
          case eff => vtpe match {
            case SinkNode | SourceNode | ArgNode => List(CstVertex(eff, loc))
            case IntermediateNode => List(CstVertex(eff, constLoc))
          }
        }
        case _ => List()
      }

      /**
        * The basic pattern for an apply:
        *          Apply
        *          / \
        *         /   \
        *      Apply  tpe2
        *       / \
        *     /    \
        *   Cst    tpe1
        *    |
        *   Op
        */
      case Type.Apply(tpe1, tpe2, _) => (tpe1, tpe2) match {
        /**
          * The "leaf" pattern :
          *           .
          *          / \
          *         /   \
          *      Apply  Var
          *       / \
          *     /    \
          *   Cst    Var
          *    |
          *   Op
          */
        case (Type.Apply(Type.Cst(tc, _), v1@Type.Var(_, _), _), v2@Type.Var(_, _)) => tc match {
          case TypeConstructor.Union => toVerticesFromType(v1, constLoc, vtpe) ::: toVerticesFromType(v2, constLoc, vtpe)
          case _ => List()
        }
        case (Type.Apply(Type.Cst(tc, _), cst@Type.Cst(_, _), _), v@Type.Var(_, _)) => tc match {
          case TypeConstructor.Union => toVerticesFromType(cst, constLoc, vtpe) ::: toVerticesFromType(v, constLoc, vtpe)
          case _ => List()
        }

        case (Type.Apply(Type.Cst(tc, _), x@Type.Cst(_, _), _), y@Type.Cst(_, _)) => tc match {
          case TypeConstructor.Union => toVerticesFromType(x, constLoc, vtpe) ::: toVerticesFromType(y, constLoc, vtpe)
          case _ => List()
        }

        /**
          * The pattern where the right-hand side is nested :
          *           .
          *          / \
          *         /   \
          *      Apply  Apply
          *       / \     ...
          *     /    \
          *   Cst    Var
          *    |
          *   Op
          */
        case (Type.Apply(Type.Cst(tc, _), v@Type.Var(_, _), _), Type.Apply(_, _, _)) =>
          tc match {
            case TypeConstructor.Union => toVerticesFromType(v, constLoc, vtpe) ::: toVerticesFromType(tpe2, constLoc, vtpe)
            case _ => List()
          }

        case (Type.Apply(Type.Cst(tc, _), v@Type.Var(_, _), _), cst@Type.Cst(_, _)) =>
          tc match {
            case TypeConstructor.Union =>  toVerticesFromType(v, constLoc, vtpe) ::: toVerticesFromType(cst, constLoc, vtpe)
            case _ => List()
          }

        /**
          * The pattern where the left-hand side is nested :
          *           .
          *          / \
          *         /   \
          *      Apply  Var
          *       / \
          *     /    \
          *   Cst    Apply
          *    |       ...
          *   Op
          */
        case (Type.Apply(Type.Cst(tc, _), nested@Type.Apply(_, _, _), _), v@Type.Var(_, _)) =>
          tc match {
            case TypeConstructor.Union => toVerticesFromType(v, constLoc, vtpe) ::: toVerticesFromType(nested, constLoc, vtpe)
            case _ => List()
          }

        case (Type.Apply(Type.Cst(tc, _), nested@Type.Apply(_, _, _), _), cst@Type.Cst(_, _)) =>
          tc match {
            case TypeConstructor.Union => toVerticesFromType(cst, constLoc, vtpe) ::: toVerticesFromType(nested, constLoc, vtpe)
            case _ => List()
          }

        case (Type.Apply(Type.Cst(tc, _), cst@Type.Cst(_, _), _), nested@Type.Apply(_, _, _)) =>
          tc match {
            case TypeConstructor.Union => toVerticesFromType(cst, constLoc, vtpe) ::: toVerticesFromType(nested, constLoc, vtpe)
            case _ => List()
          }

        case (Type.Apply(Type.Cst(tc, _), nested1@Type.Apply(_, _, _), _), nested2@Type.Apply(_, _, _)) =>
          tc match {
            case TypeConstructor.Union => toVerticesFromType(nested1, constLoc, vtpe) ::: toVerticesFromType(nested2, constLoc, vtpe)
            case _ => List()
          }

        case _ => List()
      }
      case _ => List()
    }

    vtpe match {
      case ArgNode => List(ArgVertex(toVerticesFromType(tpe, constLoc, vtpe), constLoc))
      case SinkNode => List(SignatureVertex(toVerticesFromType(tpe, constLoc, vtpe), constLoc))
      case IntermediateNode => toVerticesFromType(tpe, constLoc, vtpe)
      case SourceNode => toVerticesFromType(tpe, constLoc, vtpe)
    }
  }
}
