mod Test.Exp.Int32 {

    @Test
    def testInt32_01(): Int32 = -254542i32

    @Test
    def testInt32_02(): Int32 = 45649878i32

    @Test
    def testInt32_03(): Int32 = -32769i32

    @Test
    def testInt32_04(): Int32 = 32768i32

    @Test
    def testInt32_05(): Int32 = 2147483647i32

    @Test
    def testInt32_06(): Int32 = -2147483648i32

    @Test
    def testInt32_07(): Int32 = 1_0i32

    @Test
    def testInt32_08(): Int32 = 1_000i32

    @Test
    def testInt32_09(): Int32 = 42_000i32

    @Test
    def testInt32_10(): Int32 = 1_000_000i32

    @Test
    def testInt32_11(): Int32 = 42_000_000i32

    @Test
    def testInt32_12(): Int32 = 1_000_000_000i32

    @Test
    def testInt32_13(): Int32 = 0x1ABCDEF9i32

    @Test
    def testInt32_14(): Int32 = 0x1A_BC_DE_F9i32

    @Test
    def testInt32_15(): Int32 = 0x0i32

    @Test
    def testInt32_16(): Int32 = 0x1i32

    @Test
    def testInt32_17(): Int32 = 0x1abcdef9i32

    @Test
    def testInt32_18(): Int32 = 0x1a_bc_de_f9i32

}
