mod Test.Exp.Int8 {

    @Test
    def testInt8_01(): Int8 = -105i8

    @Test
    def testInt8_02(): Int8 = 121i8

    @Test
    def testInt8_03(): Int8 = -2i8

    @Test
    def testInt8_04(): Int8 = 6i8

    @Test
    def testInt8_05(): Int8 = 127i8

    @Test
    def testInt8_06(): Int8 = -128i8

    @Test
    def testInt8_07(): Int8 = 1_0i8

    @Test
    def testInt8_08(): Int8 = 1_00i8

    @Test
    def testInt8_09(): Int8 = 0x1Ai8

    @Test
    def testInt8_10(): Int8 = 0x1_Ai8

    @Test
    def testInt8_11(): Int8 = 0x0i8

    @Test
    def testInt8_12(): Int8 = 0x1i8

    @Test
    def testInt8_13(): Int8 = 0x1ai8

    @Test
    def testInt8_14(): Int8 = 0x1_ai8

}
