mod Test.Lit.Int8 {

    @CompileTest
    def int8Lit01(): Int8 = -105i8

    @CompileTest
    def int8Lit02(): Int8 = 121i8

    @CompileTest
    def int8Lit03(): Int8 = -2i8

    @CompileTest
    def int8Lit04(): Int8 = 6i8

    @CompileTest
    def int8Lit05(): Int8 = 127i8

    @CompileTest
    def int8Lit06(): Int8 = -128i8

    @CompileTest
    def int8Lit07(): Int8 = 1_0i8

    @CompileTest
    def int8Lit08(): Int8 = 1_00i8

    @CompileTest
    def int8Lit09(): Int8 = 0x1Ai8

    @CompileTest
    def int8Lit10(): Int8 = 0x1_Ai8

    @CompileTest
    def int8Lit11(): Int8 = 0x0i8

    @CompileTest
    def int8Lit12(): Int8 = 0x1i8

    @CompileTest
    def int8Lit13(): Int8 = 0x1ai8

    @CompileTest
    def int8Lit14(): Int8 = 0x1_ai8

}
