mod Test.Lit.Int16 {

    @CompileTest
    def int16Lit01(): Int16 = -5320i16

    @CompileTest
    def int16Lit02(): Int16 = 4568i16

    @CompileTest
    def int16Lit03(): Int16 = -129i16

    @CompileTest
    def int16Lit04(): Int16 = 128i16

    @CompileTest
    def int16Lit05(): Int16 = 32767i16

    @CompileTest
    def int16Lit06(): Int16 = -32768i16

    @CompileTest
    def int16Lit07(): Int16 = 1_0i16

    @CompileTest
    def int16Lit08(): Int16 = 1_000i16

    @CompileTest
    def int16Lit09(): Int16 = 32_000i16

    @CompileTest
    def int16Lit10(): Int16 = 0x1ABCi16

    @CompileTest
    def int16Lit11(): Int16 = 0x1A_BCi16

    @CompileTest
    def int16Lit12(): Int16 = 0x0i16

    @CompileTest
    def int16Lit13(): Int16 = 0x1i16

    @CompileTest
    def int16Lit14(): Int16 = 0x1abci16

    @CompileTest
    def int16Lit15(): Int16 = 0x1a_bci16

}
