@test
def testArrayLit01(): Array[Unit] = []

@test
def testArrayLit02(): Array[Int] = [1]

@test
def testArrayLit03(): Array[Int] = [1, 2, 3]

@test
def testArrayLit04(): Array[Int] = [1,2,3,4]

@test
def testArrayLit05(): Array[Int] = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

@test
def testArrayLit06(): Array[Int] = [1,2]

@test
def testArrayLit07(): Array[Bool] = [true]

@test
def testArrayLit08(): Array[Bool] = [false]

@test
def testArrayLit09(): Array[Bool] = [true, false]

@test
def testArrayLit10(): Array[Bool] = [false, true, false]

@test
def testArrayLit11(): Array[Bool] = [false, false, false, false, true]

@test
def testArrayLit12(): Array[Char] = ['c']

@test
def testArrayLit13(): Array[Char] = ['a', 'b']

@test
def testArrayLit14(): Array[Char] = ['a', 'b', 'c']

@test
def testArrayLit15(): Array[Char] = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']

@test
def testArrayLit16(): Array[Int8] = [1i8]

@test
def testArrayLit17(): Array[Int8] = [1i8, 2i8, 3i8]

@test
def testArrayLit18(): Array[Int8] = [1i8,2i8,3i8,4i8]

@test
def testArrayLit19(): Array[Int16] = [1i16]

@test
def testArrayLit20(): Array[Int16] = [1i16, 2i16, 3i16]

@test
def testArrayLit21(): Array[Int16] = [1i16,2i16,3i16,4i16]

@test
def testArrayLit22(): Array[Int64] = [1i64]

@test
def testArrayLit23(): Array[Int64] = [1i64, 2i64, 3i64]

@test
def testArrayLit24(): Array[Int64] = [1i64,2i64,3i64,4i64]

@test
def testArrayLit25(): Array[Float32] = [1.0f32]

@test
def testArrayLit26(): Array[Float32] = [1.0f32, 2.0f32, 3.0f32]

@test
def testArrayLit27(): Array[Float32] = [1.0f32,2.0f32,3.0f32,4.0f32]

@test
def testArrayLit28(): Array[Float64] = [1.0f64]

@test
def testArrayLit29(): Array[Float64] = [1.0f64, 2.0f64, 3.0f64]

@test
def testArrayLit30(): Array[Float64] = [1.0f64,2.0f64,3.0f64,4.0f64]

@test
def testArrayLit31(): Array[Str] = ["Hello"]

@test
def testArrayLit32(): Array[Str] = ["Hello", "World"]

@test
def testArrayLit33(): Array[Str] = ["World", "Hello", "World"]

@test
def testArrayLit34(): Array[Array[Int]] = [[1,2,3]]

@test
def testArrayLit35(): Array[Array[Int]] = [[1,2], [1,2]]

@test
def testArrayLit36(): Array[Array[Int]] = [[1], [1,2,3,4,5,6,7,8]]

@test
def testArrayLit37(): Array[Array[Int]] = [[1,2,3,4,5], [2]]

@test
def testArrayLit38(): Array[Array[Int]] = [[1,2,3], [1,2,3], [1,2,3]]

