/*
 * Copyright 2015-2016 Magnus Madsen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix.util

object Options {
  /**
    * Default options.
    */
  val Default = Options(
    debugger = Debugger.Disabled,
    Nil,
    verbosity = Verbosity.Silent,
    verify = Verify.Disabled,
    codegen = CodeGeneration.Enabled,
    debugBytecode = DebugBytecode.Disabled
  )
}

/**
  * General Flix options.
  *
  * @param debugger      enable or disable the built-in web-based debugger.
  * @param print         a list of things to print.
  * @param verbosity     the level of verbosity.
  * @param verify        enable or disable the built-in verifier.
  * @param codegen       enable or disable JVM code generation.
  * @param debugBytecode enable or disable debugging of bytecode.
  */
case class Options(debugger: Debugger,
                   print: List[String],
                   verbosity: Verbosity,
                   verify: Verify,
                   codegen: CodeGeneration,
                   debugBytecode: DebugBytecode)


/**
  * An option to enable or disable the built-in web-based debugger.
  *
  * Note: Enabling the debugger may incur a significant performance overhead.
  */
sealed trait Debugger

object Debugger {

  /**
    * Enables the built-in web-based debugger.
    */
  case object Enabled extends Debugger

  /**
    * Disables the built-in web-based debugger.
    */
  case object Disabled extends Debugger

}

/**
  * An option to control the level of verbosity.
  */
sealed trait Verbosity

object Verbosity {

  /**
    * Output verbose information. Useful for debugging.
    */
  case object Verbose extends Verbosity

  /**
    * Output condensed information. The default.
    */
  case object Normal extends Verbosity

  /**
    * Output nothing. Useful for when Flix is used as a library.
    */
  case object Silent extends Verbosity

}

/**
  * An option to control whether verification is enabled.
  */
sealed trait Verify

object Verify {

  /**
    * Enables the built-in verifier.
    */
  case object Enabled extends Verify

  /**
    * Disables the built-in verifier.
    */
  case object Disabled extends Verify

}

sealed trait CodeGeneration

object CodeGeneration {

  /**
    * Enables JVM code generation of Flix functions.
    */
  case object Enabled extends CodeGeneration

  /**
    * Disables JVM code generation of Flix functions.
    */
  case object Disabled extends CodeGeneration

}

sealed trait DebugBytecode

object DebugBytecode {

  /**
    * Enables debugging of bytecode, by dumping generated bytecode to files.
    */
  case object Enabled extends DebugBytecode

  /**
    * Disables debugging of bytecode.
    */
  case object Disabled extends DebugBytecode

}
