name: Completion Invariant

on: [ pull_request, merge_group ]

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: completion-invariant-${{ github.ref }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xms128m -Xmx4g"

    steps:
      - name: Check out master
        uses: actions/checkout@v4
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with gradle
        run: ./gradlew clean compileTestScala --console=plain
      - name: Test with timeout
        timeout-minutes: 20
        run: ./gradlew testCompletionInvariant --console=plain
