name: First Interaction

on:
  pull_request:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v2.0.0
        with:
          pr_message: |
            Thanks for your contribution.
            
            If you haven't already, please be sure to add your name to `AUTHORS.md` to indicate that you release your contributions under the Apache 2.0 license.
